# -*- mode:org; -*-

#+title:Resources and Notes Relating to Estate Planning and Drafting
#+subtitle:{{{version}}} {{{date}}}
#+author:LOLH
#+date:2020-11-12 16:43
#+macro:version Version 0.0.6
#+macro:upload-date (eval (current-time-string))
#+bucket:wa-legal.com

{{{version}}} {{{date}}}

#+texinfo:@insertcopying


* Introduction
:PROPERTIES:
:unnumbered: t
:END:
* Resources
** Estate Planning and Drafting (3rd Edition 2007) by Regis W. Campfield
:PROPERTIES:
:custom_id: EPaD3
:END:
** Drafting Legal Documents---Principles and Practices (2nd Edition 1992) by Barbara Child
:PROPERTIES:
:custom_id: DLDPaP
:END:
* Estate Planning and Drafting 3rd
** Part 0 --- Preliminary
*** Chapter---Introduction
**** A [¶1001] ---Objectives
**** B [¶1051] ---Motivations
**** C [¶1061] ---Role of Estate ("Death") Taxation
**** D [¶1081] ---Role of Income Taxation
**** E [¶1101] ---Organization
**** F [¶1201] ---Schematic Illustrations
**** G [¶1301] ---Tax Sheltering the Tax-Free Amount---The Story of Hubby and Wifie and Chad and Dimples
**** H [¶1401] ---Bypass the Children? The Story of Biff and Bunny and Fred and Gertrude
** Part I   --- Living and Dying
*** Chapter---Counseling the Client
**** A [¶2001] --- Objectives
#+cindex:counselor at law
#+cindex:counseling
Lawyers as /counselors/ at law. The basic questions: /what is counseling?/

This chapter presents a discussion of some  of the major issues involved in the
role of the estate and trust lawyer as counselor.

The reader is free to draw  own definition of counseling. The significant point
is that counseling  is an integral, inescapable part of  the lawyer's role.  It
is the most difficult, yet the most gratifying, of the lawyer's tasks.
**** B [¶2051] --- What Do You Need to Know?
***** [¶2051] Introduction
Counseling  in  an  estate  planning  context  is  the  process  by  which  the
professional determines what it is that the  client wants to do with his or her
property at deathtime.  Some clients will  want to make lifetime transfers, but
most will want to keep control of their property until death.

Re: counseling will-making clients...

Is  the counseling  objective fundamentally  to  determine the  answer to  four
questions:

1. *Beneficiary*: To whom does the testator want to give his or her property?
2. *Executor*: Who is to be executor of the testator's death?
3. *Parental Guardian*: Who is to  be the "parental guardian" of the testator's
   minor children in the event of premature death?
4. *Tax Planning*: Does the testator need tax planning advice?

***** [¶2059] Who is the Beneficiary?
#+cindex:beneficiary
For most, the  beneficiary is "my spouse  if my spouse survives me;  if not, my
children."

In cases where  the client expresses a different disposative  scheme, time must
be given to "classification" of the client's property.  See ¶11,051.

****** [¶2065] Problem
Consider how best to go about  learning about the dispositive scheme the client
has chosen.  Should  you open the interview by asking  detailed questions about
the client's fammiily  and property? Or is the best  approach to open theformal
conversation by asking simply, "To whomdo you want to give your property?"

***** [¶2067] Who is to be "Executor" and Who is to be "Guardian"?
#+cindex:executor
#+cindex:guardian
Oftentimes the principal motivation for making a will is "to appoint a guardian
for our son and daughter in case anything happens to us."  See ¶3601 and ¶4051.

****** [¶2073] Problem
Consult ¶3051 and determine whether the  advantages of dying testate as opposed
to intestate  are sufficiently significant  that the client should  be strongly
urged to proceed  with the will-making while deferring a  decision on either or
both the guardian or executor question.

***** [¶2075] Is Tax Planning Necessary?

****** Death Costs

****** Valuation

****** Classification

****** [¶2100] Problem

**** C [¶2151] --- What Are Your Responsibilities?
***** [¶2151] Estate Planning
A certain minimum level of sophistication is required to counsel clients in the
area of estate planning.
****** Statement of Principles of the Estate Planning Attorney in Texas
- From 41 Tex. B.J. 169, 169-72 (1978), by Robert Bandy
******* What is Estate Planning?
#+cindex:Estate Planning
"Estate Planning"  is the process by  which the client plans  the accumulation,
management, conservation,  and disposition of his  or her estate so  that he or
she and beneficiaries  will derive the maximum benefit  during their lifetimes.
This process  requires coordination and  integration of the  client's personal,
financial and business affairs.
******* What are the Specific Skills?
#+cindex:skills
In order for an individual to hold himself out tothe public as an estate
planner:
- he  must be  thoroughly  skilled  in the  law  pertaining  to wills,  trusts,
  property rights and estates;
- he must be capable of concise and unambiguous draftsmanship;
- he must understand the broad trends and the applicable rules of income,
  estate, inheritance and gift taxation;
- he should be acquainted with the practices and customs of the professional
  fiduciaries in his area;
- he should be schooled in the law of business entities and be prepared to
  continue, dispose of, or dismember a business;
- he should be familiar with the essentials pertaining to pension and profit
  sharing plans and deferred compensation arrangements;
- he must have knowledge and experience and be familiar with the basic
  essentials of investments, insurance and accounting, and the sources of
  specialized advice in these areas;
- he should have a good understanding of the basic principles of business
  operations and financing;
- he should be a counselor with a good understanding of psychology;
- and finally, he should be willing to cooperate with other members of the
  estate planning team in the creation and implementation of the estate plan.


The foregoing  comprehensive capabilities  demonstrate how  difficult it  is to
become a proficient  estate planner.  Mastery of these essential  skills by one
person is an enormous undertaking.
******* Who Does Estate Planning?
******* What is the Responsibility of the Non-Specialist Practitioner?
******* What Legal Tasks Should Be the Lawyer's Responsibility?
******** Legal Tasks
1. Data Gathering and Determination of Client Objectives
   a. Family
      - information concerning family, including the identities, ages, and
        relationships of members of immediate family and those of collateral
        relatives
   b. Legal Relationships
      - information concerning legal relationships or unusual family matters
        which may affect the client's estate plan, including
	- existence of prior marriages of the client or spouse,
	- existence of property settlement agreements, court orders, other
          agreements concerning prior marriages or client or spouse,
	- existence of health problems or other matters affecting particular
          family members
   c. Estate Assets
      - information to determine the
	- identity
	- location
	- approximate value
	of client's estate assets
   d. Ownership
      - information (including actual documents where appropriate) necessary to
        determine the existing ownership and title arrangements with respect to
        the  client's estate  assets, including  co-ownership and  survivorship
        arrangments.
   e. Characterization
      - information necessary to determine the community or separate property
        characterization and information relating to management and control of
        the client's estate assets
   f. Contracts
      - information concerning any joint and mutual will, contracts to will, or
        other legal impediments to dispose freely of the client's estate assets
   g. Current Estate Plan
      - determine existence and nature of the client's present estate planning
        arrangments, including
	- business succession agreements
	- survivorship arrangements
	- beneficiary or other designations with regard to insurance, employee
          benefits, or other estate assets
      - whether existing documents are satisfactory, or are capable of being
        modified through trust amendment or codicil;
      - whether they contain any libelous material or matter which would be in
        poor taste as a public record;
      - whether existing will  and codicils appear to be  properly executed and
        self-proved;
      - whether theclient has advised proposed fiduciaries of their
        appointment and provided any needed guidelines for exercise of
        fiduciary discretion;
      - whether all original executed copies of existing estate planning
        documents are readily available if needed;
   h. Other's Current Estate Plans
      - existence and nature of estate plans of other persons, living or
        deceased, which affect the clients estate plan, including other wills,
        trust agreements, powers of appointment, and beneficiary designations
   i. Review Client's Current Estate Planning Documents
   j. Dispositive Wishes
      - determine client's desires and objectives regarding the disposition of
        estate assets
   k. Fiduciary Wishes

***** [¶2159] Financial Planning
***** [¶2169] Malpractice

**** D [¶2201] --- Why Clients Elect to Make Wills
**** E [¶2251] --- The Counseling Function
**** F [¶2301] --- Client Interviews
**** G [¶2351] --- Gathering Information
The obvious question is "how do you gather the required information?"

This is the counseling function.

Do you do this in the context of  a formal conference with the client or do you
send out a questionnaire which raises these questions and directs the client to
contact your office once he or she has completed the questionnaire?

Alternatively,  do you  arrange a  formal meeting  with the  client and,  after
greetings are  exchanged, hand the client  over to a paralegal  who will gather
the required information  and prepare a memorandum for  your review summarizing
the information relevant to the preparation of the dispositive instruments?
**** H [¶2401] --- Fees for Estate Planning Services
**** I [¶2451] --- Conflict of Interest in Spousal Representation
**** [¶2461] --- Problems
1. ...
2. ...
3. ...
*** Chapter---Will Planning
**** A---Objectives
**** B---The Need for a Will
**** C---Organizational Scheme for the Will
**** D---Payment of Debts and Administration Expenses
**** E---Tax Allocation Clauses
**** F---Specific Bequests in General
**** G---Tangible Personal Property and Personal Residencie
**** H---Property Subject to Indebtedness
**** I---Lapse and Close Order of Death
**** J---Gifts to Lineal Descendents
**** K---Per Stirpes and the Root Generaion Clause
**** L---Selection of Executor
**** M---Conflicts of Law
**** N---Avoiding Ancillary Administration
**** O---Anatomical Gifts
*** Chapter---Powers of Attorney--Advance Directives--Living Trusts---Disability Planning
**** A---Objectives
**** B---Guardiandship of Incompetents
**** C---Durable Powers of Attorney
**** D---The Standby Revocable Trust and Limited-Powers for Disability
**** E---The Backup Trust for Beneficiaries Under Legal Disability--Alternatives
**** F---Nature of a Trust
**** G---Elements of a Trust
**** H---Pourover Wills
**** I---The Illusory Trust Doctrine
**** J---Claims of the Surviving Spouse
*** Chapter---Drafting for Successive Enjoyment
**** A---Objectives
**** B---Common Dispositive Scheme
**** C---Background
**** D---Gifts to Heirs
**** E---Express and Implied Conditions of Survivorship
**** F---Class Gifts
**** G---Death Without Issue
**** H---The Rule Against Perpetuities
** Part II  --- Tax Considerations
** Part III --- Transfers for the Benefit of the Transferor
** Part IV  --- Spousal Gifts and Disclaimers
** Part V   --- The Bypass Trust and Related Gift Planning
** Part VI  --- Special Situations
** Part VII --- Financial and Retirement Compensation Planning
** Appendices
:PROPERTIES:
:appendix: t
:END:
*** Electronic Sources
*** Projects
* Drafting Legal Documents 2nd
* Information Forms
** Your Estate Planning Portfolio
#+title:Estate Planning Questionnaire
#+subtitle:Helping You Plan for and Document Your Estate Throughout the Years
#+author: Law Office of Lincoln Harvey
#+date: \today

Hello.  I offer a different perspective  on the estate planning process than is
normally encountered.  The following process has two primary goals:

1. Guide you  while you are alive in  easily setting up and keeping  up to date
   your estate plan; and
2.  Assist  your loved  ones after  you pass in  handling your  estate quickly,
   efficiently, and cost-effectively.


As you prepare your state of affairs,  keep those two perspectives in mind, and
the following process will become something  you look forward to doing, and not
a chore or something you put off year  after year until too late.

\section*{The Rationale}

\emph{Planning  your estate  should  be  personal to  you.}   It  should be  an
on-going process that you always have up-to-date and under control, and that is
easy to work with and not a chore that gets put off.  Looked at another way, it
is something that  \emph{only} you can do,  and it needs to  be done regularly.
This process should  \emph{never} interfere with nor prevent you  from having a
complete estate  plan in place  that you are happy  with, nor from  quickly and
easily updating it to take account of changing circumstances, both your own and
the  legal  and  financial  landscapes.    Put  something  in  place,  give  it
consideration,  ask  questions of  your  advisors,  and make  adjustments  when
necessary.   Remember  that most  documents  can  have codicils  or  amendments
drafted quickly and affordably instead of having to redo everything.

\section*{The Process}

Below are  some categories and questions.   What you should do  is prepare your
own  document  on  your own  word  processing  program,  and  place in  it  the
information that is pertinent to you in your own words.  Many of the categories
will have  source documents  that provide  the necessary  detail, such  as 401K
quarterly statements,  your bank  account year-end  statements, home  title and
loan  documents, and  car titles,  etc..  Obtain  the latest  source documents,
print out  your information, place it  into a 3-ring binder  with dividers, and
place the  source documents  inside.  Each  year, as  a New  Year's resolution,
update the  document and its  source documents and  give your estate  plan some
thought.

As time goes  on, just add updated documents, update  your master document, and
your estate plan  will always stay in focus.  Never  throw any source documents
away, and you will  have a living history of your  estate throughout the years.
There is no need  to keep every source document that comes in  the mail, but at
least keep yearly accounts  up-to-date.  You will be able to  tell the state of
your affairs at any time with just a  quick glance, and you can show it to your
advisors and they  will be instantly aware  of what they need to  know, or will
let you know if you are missing something.

Each category below should start on a new  page, so when it comes time to print
an updated  version, you  just need to  print what has  changed, not  the whole
thing.   Place copies  of estate  documents, such  as your  will and  powers of
attorney, in  the binder, and place  the originals in  a safe deposit box  in a
bank or  fireproof safe at  home.  Also place in  the safe deposit  box account
names  and  passwords  to  online  accounts  of  your  financial  matters  with
references to them in the binder.  Anything and everything that is important to
\emph{you}  should go  into this  binder or  into a  safe deposit  box, with  a
reference from the binder.

\section*{In Summary}

The categories  are suggestions.  Nothing written  below is set in  stone; feel
free to change, add to, and subtract  from what is there.  What is important is
that this information reflect you at  the present moment, and provide a history
of where you have been over the years to help guide you and your advisers going
forward.

\bfseries  Remember that  another goal  is that  after you  pass away  and your
family begins  the proces of  handling your  estate, they will  have everything
they need in your estate binder to quickly, efficiently and cost-effectively do
the job nobody wants  to do. \normalfont There is a peace  of mind from knowing
you have done everything you could to make that process easy for them when they
have to do it.

\newpage

*** Personal Information
**** You
1. Full Legal Name
2. Citizenship
3. Mailing Address
4. Residence Address
5. Work Address
6. Phone Numbers
   1. Mobile
   2. Work
   3. Home
7. Email Addresses
   1. Home
   2. Work
   3. Others
8. Marital Status
   1. Single
   2. Married
   3. Divorced
   4. Married and Divorced
   5. Partner
9. Date and place of birth
10. Location of Family records
11. Your Financial Advisors
    1. Lawyers
    2. Accountants
    3. Tax Professionals
    4. Life Insurance Agents
    5. Fiduciaries
12. Medical Advisors
    1. Personal Physician
    2. Specialists
    3. Chiropractors
    5. Others
13. Former Residences and dates
List places you have lived since adulthood, dates, and with whom you lived.
14. Former Marriages
    1. Name of Ex's
    2. DOMs
    3. POMs
    4. DODivorces
    5. PODivorces
    6. Court documents
    7. Children of marriages
**** Your Spouse or Partner
1. Full Legal Name
2. Citizenship
3. Mailing Address
4. Residence Address
5. Work Address
6. Phone Numbers
*** Familiy Information
**** Natural and Adopted Children and Legal Dependents
1. Names
2. DOBs
3. DODs
4. Mailing Addresses
5. Residence Addresses
6. Parents
7. Marital Status
8. Children
**** Disabilities and Incapacities with You and Family Members
*** Property
**** Titled property
Obtain most current titled documents for each item listed.
***** Main residence
***** Vacation home
***** Income properties
***** Co-owned properties
***** Main car
***** Secondary cars
***** Recreational vehicles
***** Motorcycles
***** Co-owned vehicles
**** Significant items of property
Obtain picture if possible of each item listed.
***** Jewelry
***** Art
***** Heirlooms
***** Other
**** Long-term leases
Obtain most recent document
**** Judgments you hold
Obtain most recent document
**** Accounts receivable
Obtain most recent documents
*** Liabilities
**** Home loans
Most recent documents
**** Secondary home loans
Most recent documents
**** Car loans
Most recent documents
**** Medical liabilities
Most recent documents
**** Contract liabilities
Most recent documents
**** Credit card liabilities
Most recent documents
**** Judgments against you
Most recent documents
**** Ongoing litigation
*** Retirement and Personal Savings Assets
Most recent documents of each listed account
**** 401K accounts
**** Pensions
**** IRAs
**** Retirement Investments
**** Profit Sharing Plans
**** Stock Options
**** QDROs from prior divorces
*** Financial Information
If your estimated  net worth is greater than $2M,  request the Financial Status
Questionnaire
**** Taxes
***** W2s
***** 1099s
***** Tax returns from past years
If you  do not have  copies, you can  request summaries from  the IRS at  no to
little cost.
**** Banks and Credit Unions
***** Checking Accounts
***** Savings Accounts
***** Other
**** Investments
***** Stocks
***** Mutual Funds
***** Bonds
**** Businesses
*** Expected Inheritances
List any inheritances expected in the future.
*** Charitable Giving
Do you wish to make charitable bequests?
*** Prior Gifts
List gifts previously made that exceeded $11,000.
*** Living Trust
Are you interested in a living trust?  Why?
*** Information for your Will
**** Personal Representatives
**** Trustees for minor children
**** Guardians for minor children
*** Information for your Powers of Attorney
**** POA for Medical Matters
***** Agents
***** Powers
***** Restrictions
**** POA for Financial Matters
***** Agents
***** Powers
***** Restrictions
*** Information for your Health Care Directive (Living Will)
Your  wishes in  the event  of an  incurable illness  or permanent  unconscious
condition.

- Withdraw life-sustaining procedures?
  - Withdraw nutrition?
  - Withdraw hydration?
  - Withdraw both nutrition and hydration?
  - Withdraw neither?
- Do Not Resuscitate (DNR)?
- Do Not Attempt Resuscitation (DNAR)?
- If you are female and pregnant?
  - Life-sustaining procedures?
  - DNR?
  - DNAR?
- Organ donor?
  - Research and Education also?
*** Information for Final Arrangements
**** Funeral arrangements
**** Memorial arrangments
**** Cremation arrangements
**** Burial arrangements
**** Interment arrangements

*** Your Estate Planning Goals in your Words
So...  after preparing  all of  the foregoing,  what are  your estate  planning
goals?  Summarize your estate planning goals in your own words, and include any
questions you have about any aspect of the estate planning process.
*** Copies of your Estate Planning Documents
**** Will
**** Codicils
**** Power of Attorney for Financial Management
**** Power of Attorney for Health Care Management
**** HIPPA Forms
**** Health Care Directive (Living Will)
**** Living Trust
**** Special Needs Trust
**** Irrevocable Trust
*** Copies of your Medical Documents
**** Annual checkups
**** Prescriptions
**** Medications
**** Special Procedures
**** Surgeries
**** Hospitalizations
* Articles on Specific Subjects
** Estate Planning
*** Robb's Easy Overview
:PROPERTIES:
:cite:     http://www.robblaw.com/html/estate_planning.html
:author:   John Robb
:END:
ESTATE PLANNING: ROBB'S EASY OVERVIEW...

In its simple form, estate planning deals  with how to pass property to someone
else when  you die. There  are several methods and  we will outline  them here.
These  methods are  all separate  and independent  of each  other. This  is not
intended to  be an exhaustive  outline and there  are always exceptions  to all
rules.   We   would  be   happy  to  answer   questions  about   your  specific
situation. Just drop us  an email or make an appointment to come  in for a more
detailed explanation. As in everything we do,  your matters will be kept in the
utmost confidence.

METHOD NUMBER 1.

JOINT TENANCY OWNERSHIP.

You can  own property with  another person and title  it as joint  tenants with
rights of survivorship and not as tenants in common.  This means that the title
is held in two or more names and contain the magic words "joint tenants."  This
form of  ownership instantly and  automatically transfers property at  death to
the surviving owners.  It  is not the fact that there are two  or more names on
the  property that  make this  work.  It works  due  to the  magic words  joint
tenancy. If the magic  words are not present then this will  not work.  The law
specifically presumes that you did not intend  to create a joint tenancy if the
words are not present.

The account  is titled John Doe  and Mary Doe  as joint tenants with  rights of
survivorship and not as tenants in common.

Advantages:

l  With this form of ownership no lawyers are usually needed at death.

l  Property does not have to go through the probate court at death.

l  It is simple to understand and set up.

l  It is an inexpensive planning tool.

l  The property transfer is instant and automatic at death. 

Disadvantages:

l Joint tenancy does not apply to all property types.

l It is an item by item plan.  The title to each asset must contain the names of the co-owners and the magic words must be present. Every time you change your mind you have to change the title to all of the assets involved.

l Because it is so simple and easy, joint tenancy has the potential for misuse.

l It should  NOT be used instead of a power of attorney to gain help in paying your bills.

l It can require the consent of all owners to deal with your property. You may have to get your children's permission to cash an investment.

l Joint tenancy property may be subject to the creditors of any owners.  This means that a garnishment intended for one of your children may tie up your property.

l Joint tenancy property may become entangled with property division by a divorce court of any owner.  A lawyer can usually extract it from the court but it may cost time and money.

l Joint tenancy can have disastrous Federal Estate Tax results in some situations.

l  If all assets are titled in this fashion, there is no fund from which to pay your last expenses.  Each of the beneficiaries must contribute back to some common fund for the payment of bills and the funeral.

l  Joint tenancy carries with it no protection for minors. The minor cannot legally deal with it and it may require that a conservator be appointed to deal on behalf of the minor.

l Your intended recipients may get left out if a joint tenant dies before you do.  It will leave out your grandkids from that child and leave it all to the surviving joint tenants.

It works rather well for passing property between husband and wife with estates that are not taxable.  There are probably better methods for other situations.

METHOD NUMBER 2.

BENEFICIARY DESIGNATIONS. 

This  method only  applies to  certain types  of property.   Examples are  life
insurance, IRA accounts, retirement plans, 401k plans, Keogh plans, POD (Pay On
Death) and TOD (Transfer On Death) accounts, TOD (Transfer On Death) deeds, and
TOD (Transfer On Death) car titles.  The  title to the property remains in your
name and you designate a beneficiary to receive the property at your death.

The account is titled John Doe, pay on death to Suzy Doe.

Advantages:

l Usually no lawyers are necessary to set up this method.

l Asset transfers instantly and automatically at death.

l No probate court proceeding is necessary at death.

l  It is simple to understand and set up.

l  It is an inexpensive planning tool.

Disadvantages:

l Beneficiary designations do not apply to all property types.

l  It is an item by item plan.  The title to each asset must be placed in this form and a beneficiary named. Every time you change your mind you must change the beneficiary designations on all of the assets involved.

l Can be a challenge to treat all children equally.

l  Because it is so simple and easy, it has the potential for misuse.

l  If all assets are titled in this fashion, there is no fund from which to pay last expenses.  Each of the beneficiaries must contribute back to some common fund for the payment of bills and the funeral.

l  It can have disastrous Federal Estate Tax consequences in some estates.

l  It carries with it no protection for minors. The minor cannot legally deal with it and it may require that a conservator be appointed to deal on behalf of the minor.

l Your intended recipients may get left out if a beneficiary dies before you do.  It will leave out your grandkids from that child and leave it all to the surviving beneficiaries.

l Special beneficiary designations can be very difficult to get set up. 

METHOD NUMBER 3.

WILLS.

A will is a document that expresses where you would like your property to go at
your  death. These  documents require  strict formalities  to be  valid.  If  a
formality is  not followed, the  will can  be void. The  manner in which  it is
signed must  adhere to  a very  strict procedure.   This is  not the  place for
do-it-yourself  documents. The  plan  outlined  in your  will  does not  become
operative until your death and your will  only works on property that stands in
your name alone.  Wills  can be amended or revoked before death  as long as you
are competent. Additionally, it can  name guardians and conservators for minors
and/or can establish a trust to protect minors or disabled children.  A will is
not effective unless probated at death.  This probate process does involve both
the court and lawyers.

Advantages:

l An estate plan using a will can be fairly easily and inexpensively put together by your lawyer.

l It is a comprehensive estate plan that can dispose of all of your assets in one document. If you change your mind you just have to change one document, your will.

l Titles to assets do not have to be changed.

l You can leave all of your property in your name alone without inviting interference from children.

l A will can be changed as often as you wish without the hassle of retitling your assets at the bank.

l Charitable gifts can be included and changed from time to time in a fairly easy fashion.

l Very simple and understandable dispository language can be used: I leave all of my property to my children in equal shares.

l You can name guardians and conservators and trustees to manage matters for your minor children after you are gone.

l You can appoint who you wish to be the executor and manage your estate after your death.  This can be a responsible child or an unrelated professional.

l Estate administration can be fairly simple.  Your chosen executor inventories the property, pays your final bills and then distributes the remainder to your beneficiaries.

l An estate plan with a will is a relatively inexpensive plan at the time that you do the planning.

Disadvantages:

l At the time of death, a will must go through the probate process to be valid.  This involves using a lawyer and the court system and thus can be somewhat costly.

l The minimum time for completing the probate process is six months.  While distributions can be made within this time, the estate cannot be finally settled until the proper statutory time has elapsed.

l While your plan is very confidential during your lifetime, many matters concerning your estate are public at your death.  When your will is filed for probate it is available for the public to read.  The process requires that your executor file an inventory of your assets with the court and this is public information also.

l While an estate plan with a will may be relatively less costly at the time that you do your planning, it is relatively more costly at the time of your death due to the probate process that is involved.

METHOD NUMBER 4.

REVOCABLE LIVING TRUSTS.

A  revocable living  trust (also  known  as an  intervivos trust)  is a  signed
agreement between you  and whoever will be  your trustee.  You can  be your own
trustee  if you  wish. It  states  what happens  to your  property during  your
lifetime (the trustee will hold it, invest it, pay your bills, give back to you
if you want it back, etc.)  Then, at disability or death the trust designates a
new trustee or trustees to take over,  and at death the trust instructs trustee
to  pay your  final bills,  pay  taxes, and  distribute  what is  left to  your
beneficiaries.

An estate plan  using these trusts have  a two stage process.   First, you must
get  documents correct  and signed.  Secondly, you  must transfer  all of  your
assets to  the trust.  It  is very important to  get all assets  transferred as
major benefits are lost if assets are missed.

All plans involving revocable trusts should also have a pourover will.  This is
a will that leaves everything to your  trust.  This will serves as a safety net
in case  you forget to  place some  assets in your  trust, but it  is generally
hoped that this will is not needed  at death because all assets will already be
in the trust.

Advantages:

l The largest advantage to a revocable trust is that is avoids the probate process.  At death, your trustee simply follows the instructions set out in the trust document and settles your estate.  

l At death or disability, there is no court involvement and oftentimes very little attorney involvement.

l It is private.  Because there is no probate court process, your planning wishes and assets remain confidential.

l It is a comprehensive estate planning tool that works on your entire estate.  It is not the asset by asset process involved with joint tenancy or beneficiary methods.

l It is easy to amend or change as your intent changes. Best practice is to restate the trust rather than hook together a string of amendments and this is easily done with modern technology.

l It is the most economical plan at death. 

l This plan also provides for easy management succession during life if you become sick or disabled.  Your next named trustee simply steps up and begins to help.

l Very simple and understandable dispository language can be used: I leave all of my property to my children in equal shares.

l You can name guardians and conservators and trustees to manage matters for your minor children after you are gone.

l You can appoint anyone you wish to be the trustee. You can appoint yourself to start with and then appoint successor trustees as you wish.  Many folks appoint their children as co-trustees or successor trustees. You may also appoint an unrelated professional who has experience in handling trust matters. This sometimes relieves the stress among children revolving around power issues and arguments over who is going to be in charge.

Disadvantages:

l The trust process is more complicated at the time you do your planning. More information must be provided to your planner to get the desired end product.

l Assets must actually be transferred to the trust.  This is a very detailed oriented process that is absolutely necessary to achieve the goal of probate avoidance.  It can be a costly process depending on the assets owned. Most folks can do most of their own transfers to hold costs down.

l The documents in the trust process tend to be more complicated than a simple will.  There are many contingencies that are covered and this makes for a more complicated document set.

l The trust process normally costs more at the planning stage and less at death.  A will plan normally costs less in the planning process and more at death.

METHOD NUMBER 5.

OTHER METHODS.

While these  are not seen  as often, other  estate planning tools  include life
estate  transfers, intestate  succession  (the  state draws  a  will for  you),
irrevocable trusts, and  disclaimers. These have limited  application today and
are not in general use except for special circumstances.  As we plan estates we
will  suggest these  methods if  they seem  to be  a reasonable  approach to  a
specific estate planning problem or issue.

METHODS ARE MUTUALLY EXCLUSIVE.

Again, these  methods are all  separate and independent  of each other.   If an
asset is held in joint tenancy a will  or trust will not effect that asset.  If
a beneficiary method is used then a will does not pass that asset.  If an asset
is in  a trust  then a  will does  not pass  it.  Each  method is  separate and
independent of the other methods.

The clearest example to illustrate this principle would be a person who draws a
will and leaves everything  to my five children in equal  shares.  They then go
to the bank and add the eldest son to  all of the accounts as a joint tenant so
that they  can have  help paying their  bills if they  become ill  or disabled.
This person will think that the estate  goes to all of the children as dictated
by  the will.   Having read  this  overview you  now  know that  the elder  son
receives those assets outright as the  surviving joint tenant.  This is not the
desired result.  A little proper estate planning is needed.

Documents in a normal estate plan include a durable business power of attorney,
which allows someone  you appoint to do  business for you while  you are living
(the power ends  at your death); a durable healthcare  power of attorney, which
allows someone  you appoint  to make  healthcare decisions for  you if  you are
incapacitated; a  Living Will or Natural  Death Declaration, in which  case, if
two  doctors  agree your  condition  is  terminal,  they  are directed  not  to
artificially prolong the dying process; a will or revocable trust document; and
a pourover will (if a trust).

Benefits to this  method are that this  does avoid probate court  if all assets
held by trust, it is a comprehensive plan and easy to change, it is private (no
asset inventory  filed in  a court),  it provides  succession of  management of
affairs if become disabled during life, provides protection for minors, and has
a relatively lower cost at death.

Revocable trusts, however, have a more involved process to set up, they require
more paperwork now and transferring of titles of property to the trust now, and
they have a relatively higher cost now.

 

TAXATION ISSUES

Federal Estate  Tax - This may  be a federal tax  on your estate when  you die.
Smaller estates are exempt.  These exemptions are changing over time.

Current exemptions are:

                     2019                         $11,400,000

                     2020                         $11,580,000

This exemption is now inflaiton adjusted and will rise each year.

The current effective tax rate is 40%.

If your estate  is over these exemptions  there are ways we can  help to reduce
your estate taxes.   Particularly gifts and also  establishing separate estates
for spouses are two  of the tools we can use to shelter  a meaningful amount of
your estate  from tax.  You will  hear phrases such as  "marital bypass trusts"
and "credit  shelter trusts" which sound  much more complicated than  they are.
These are well worth exploring if your estate is in the ranges noted here.

Kansas Estate Tax Exemption Equivalent:

                      2009                         $1,000,000

                      2010 and after           No Tax

Federal Gift  Tax.  The  annual exclusion is  currently $15,000  per recipient,
meaning that there is  no gift tax or return due for these  gifts, but gift tax
returns must be filed  for all gifts over this amount.  A  husband and wife can
give $30,000  to each recipient, but  there is often  not a tax reason  to make
these gifts  until a  single estate  exceeds the  federal estate  tax exemption
amount.

Selected Income Tax issues.  Traditional IRAs and retirement plans are taxed as
you  withdraw from  them.  If  you  die and  have  assets in  these plans  your
beneficiaries pay the income tax as they withdraw the money from the plans.  If
you are in the 0% or 15% income tax bracket and your children are in the 28% or
31% bracket or higher  then it does not make much sense to  leave it to them to
pay the taxes.  Better strategy is to at  least use up the 15% tax bracket each
year by cashing some IRA assets.

 

LONG TERM CARE ISSUES

Long term care insurance.  The lifetime chances of residing in a nursing home:


This means that there is a fairly good chance that either a husband or wife may
need nursing  care at  some point  in their  lives.  There  is actually  a much
higher chance of needing nursing care than  of your house burning down or being
blown away  in a tornado  yet we all  purchase homeowners insurance.   There is
also  a much  higher chance  of needing  nursing care  than of  having a  large
liability from  an auto accident yet  we all purchase auto  insurance.Long term
care insurance can be affordable at  younger ages and becomes very expensive at
older ages. It is normally worth a visit  with an insurance agent to see what a
policy might cost and if it fits your circumstances.

Medicaid.  If a person needs nursing care and has exhausted all of their assets
then the state will pay for their  nursing care.  However, their assets must be
spent  down to  less than  $2000.  Some  items do  not count,  such as  prepaid
funeral plans, household goods, and a home if you plan to return to it.

Other things disqualify  you from Medicaid, such as too  many assets and gifts.
The lookback  period is 60 months  and gifts within this  period disqualify you
from receiving  Medicaid.  Gifts prior to  the lookback period are  not counted
against the applicant.

There is a  system for dividing assets  when one spouse needs  nursing care and
the other spouse  does not.  They allow  you to divide the assets  and when the
care-needing spouse has spent down their assets, Medicaid takes over.

Whenever  Medicaid pays  for  a person's  care  a lien  arises  for the  amount
expended against the property of the person and the person's spouse.  This lien
is not enforceable until the death of the person or their spouse.

The Medicaid  rules change  often and  care should be  taken to  seek competent
advice prior to making any of discussed changes.

SUMMARY

This overview gives you an idea of the many ways to plan an estate and stresses
the importance  of being very  careful in your  approach to estate  planning so
that you are certain to get your intent implemented.

We're happy to meet with you to review  these methods and design a plan for you
that is  efficient and cost-effective in  meeting your intent and  needs.  Feel
free to give us a call for an appointment.

 

FREQUENTLY ASKED QUESTIONS

Q. Is there a difference between a will and a living will?

A. Yes. A will is a formally signed  document that indicates who is to get your
   property at your death and who will  be in charge of paying your final bills
   and things  like that.  It can also  appoint a new  guardian for  your minor
   children if both you and your spouse die.  It has no effect whatsoever while
   you are alive.  A living will is also called a Natural Death Declaration. It
   is a formally signed document stating your intentions if you have a terminal
   condition   or  illness   and  whether   or  not   you  want   extraordinary
   life-sustaining measures employed.

Q. I have drawn my own will and signed it. Is it valid?

A. Maybe. To be valid, a will must  be signed in a certain way. It requires two
   witnesses and  that certain formalities  be followed. If  the technicalities
   are not followed,  then the will is not valid.  The technicalities vary from
   state  to  state, and  they  can  change from  year  to  year as  the  state
   legislatures change the laws.

Q. The deed to  my house has my name and my husband's  name on it. If something
   happens to one of us, will it automatically go to the survivor?

A. Maybe.  If the deed  contains the magic words  "joint tenants with  right of
   survivorship" then the  property would go to the survivor.  If the deed does
   not contain the  magic words, then the property will  not automatically pass
   to  the survivor.  The same  holds true  for titles  to other  property like
   checking accounts, cd's, stocks, savings accounts etc.

Q. What is Federal Estate Tax?

A. The federal government  may tax your estate when you die.  They base the tax
   on   all   assets   owned   by   you   at   your   death   (including   life
   insurance). Currently, the first approximate $11,500,000 per decedent passes
   to heirs  tax-free. There  are ways  for a couple  to pass  up to  twice the
   exemption amount  or more tax-free  to their  children with a  little proper
   planning.

Q. What is a living will?

A. A living will, also known as a "Natural Death Declaration, is a statement in
   writing  directing  your physician,  in  the  event  you suffer  a  terminal
   condition,  to withhold  or withdraw  life-sustaining procedures  that would
   otherwise  artificially  prolong  the   dying  process.  There  are  certain
   formalities which must be followed in making a living will and assuring that
   others  comply  with your  decisions.  This  document  is  often part  of  a
   comprehensive estate plan.

Q. What is a durable power of attorney?

A. A durable power of attorney is a written document that appoints someone else
   to make financial and other important  decisions for the person granting the
   authority. The authority granted can be  narrow and specific or more general
   and comprehensive.  This document  is often part  of a  comprehensive estate
   plan and  can be very  useful in helping  an elderly person  manage business
   affairs.

Q. What is joint tenancy?

A. Joint  tenancy is  a form of  property ownership where  two or  more persons
   share ownership  of personal  property or  real estate.  It has  the special
   attribute of "survivorship" so that when one owner dies, his or her interest
   passes automatically to the survivors.  Joint tenancy is sometimes used with
   other tools  like wills  and trusts  to achieve  a person's  estate planning
   goals. It is very appropriate in  some situations and not at all appropriate
   in other situations.

Q. My mother died 11 years ago, and  we just found her will while going through
   papers. Do we need to do anything with it?

A.  Except under  extremely limited  circumstances, a  will must  be filed  for
   probate within 6 months of death or it is void. Your mother's property would
   have passed by the  intestate succession laws of the State  of Kansas to her
   heirs.

Q. I have just moved to Kansas from  California. Do I need to change my will or
   trust?

A. It  depends. A will that  was valid where signed  should be valid in  all 50
   states. The laws of each state differ, however, and you may begin to acquire
   Kansas property that is not properly  treated in your California will. It is
   always a good practice to have a  lawyer in your new state of residence look
   at your  estate planning  documents so  you know they  still carry  out your
   plan.

Q. How do we determine how our children are raised if something happens to both
   of us?

A.  Kansas law  allows  you  to appoint  guardians  and  conservators for  your
   children in the  event of your death in  a will or trust. At  your death the
   court will appoint  whomever you chose unless they are  unfit. By exercising
   this right you can  avoid family fights over who gets the  kids, and you can
   know that your chosen person will raise your kids.

Q. I want somebody to be able to help  me pay my bills. Shouldn't I just add my
   son's name on all my accounts at the bank?

A. Probably not. By adding his name to  your account as a joint tenant you have
   given him an ownership interest in the account. His creditors may be able to
   reach  the account  or it  may  become entangled  in his  divorce action  or
   bankruptcy. At your death  the account would just belong to  your son to the
   exclusion of your other children. A  durable power of attorney that appoints
   your son is a much better way to get help paying bills.

Q. My mother just died and left me some property. Do I owe income tax on this?

A. Usually  no. Property you inherit  comes income tax-free unless  you are the
   beneficiary of an  IRA account or a  pension plan of some  sort. These items
   carry  with  them income  tax  consequences,  but  other items  come  income
   tax-free. There may be  Kansas Estate Tax or Federal Estate  Tax due in some
   cases. Proper planning can reduce or eliminate tax in many situations.

Q. I am  a widow, and for  reasons that are best  known to me, I  would like to
   leave all  of my  property to  my church rather  than to  my children  at my
   death. Can my children challenge this?

A. As long as  you are mentally competent, Kansas law allows  you to leave your
   property to anybody you wish. Children have no right to inherit in Kansas if
   you wish otherwise. The only people  who have rights to inherit are spouses;
   in Kansas you  cannot disinherit a spouse without their  consent. This is an
   area that requires close attention to details if you wish to avoid problems.

Q. I don't want them hooking me up to all those machines when I'm at the end of
   my life. Is there some way I can stop it?

A.  A Natural  Death Declaration,  or  Living Will,  is a  legal document  that
   expresses your wishes in this regard. When two doctors agree that you have a
   terminal condition and  that procedures would only  artificially prolong the
   dying process, then  this document directs that such  procedures be withheld
   or withdrawn  and that you be  permitted to die naturally.  This document is
   usually part of a well-coordinated estate plan.

Q. What is a TOD deed?

A. The Kansas legislature has authorized some  property to be held in a form of
   ownership that automatically passes the property to your named beneficiaries
   at  your  death. This  avoids  probate  but  not  taxes and  some  creditors
   claims. This  has previously  been allowed for  bank accounts,  credit union
   accounts, savings  and loan association accounts,  stock brokerage accounts,
   federal savings bonds and securities. Real  estate has now been added to the
   authorized  list. A  Transfer on  Death deed  is required  to be  signed and
   recorded to affect this kind of ownership.

Q. You have previously mentioned POD accounts and TOD deeds. How about cars and
   trucks?

A. The legislature has  authorized certain types of property to  be titled in a
   special way to  pass automatically to your beneficiaries at  your death. The
   list  includes bank  accounts,  credit union  accounts, savings  association
   accounts,  securities, brokerage  accounts, savings  bonds, real  estate and
   vehicle  titles.  This avoids  probate  but  not  taxes and  some  creditors
   claims. You  must re-register your car  title in this form  of ownership and
   send it in to have a new title issued.

Q. I recently put my assets in a revocable trust and now want to change some of
   the provisions. Is this possible?

A. Usually  yes. One of  the attributes  of a revocable  trust is that  you can
   amend  it or  revoke it  at any  time. It  is usually  a better  practice to
   restate your trust with your changes rather than string along a whole series
   of amendments. This keeps things as clear as possible as your intent changes
   over the years and avoids hurt  feelings as beneficiaries don't have to read
   that they were included and then reduced or excluded from your plan. It also
   tends to lessen chances for litigation in the interpretation of the trust.

Q. Does a person granted Power of Attorney by someone in failing health, have a
   LEGAL responsibility  to manage the finances  in a manner that  protects the
   interests of the sick person?

A. When  someone is  granted authority  under a  power of  attorney to  act for
   another,  they  probably   have  no  legal  obligation  to   act  with  that
   authority.  However, once  they  begin to  act, they  stand  in a  fiduciary
   capacity to the grantor of the power  and can be held liable for mis-uses of
   the power. The attorney in fact cannot use the power for his personal profit
   or  advantage. He  must exercise  it, if  he exercises  it at  all, for  the
   benefit of the grantor.

Q. I lost my  husband several years ago and wish to  remarry. Should I consider
   some sort of agreement so my assets will go to my kids at my death?

A. Yes. They are called Premarital Agreements  and they make good sense in your
   situation. If you  do not have an  agreement like this, your  assets may all
   wind up going to  his kids after you are gone. It  is entirely possible that
   your kids would get nothing.

Q. My  health is  failing and  I am considering  a nursing  home. Is  there any
   reason I should not give all of my assets to my kids?

A. Yes. Medicaid will pay for your nursing home care if you run out of your own
   assets.  Medicaid rules  disqualify you  if you  have made  gifts within  60
   months  of  applying. This  is  a  very complicated  area  of  the law  with
   ever-changing rules. I would highly recommend  that you speak to a qualified
   attorney prior to making the gifts.

Q. Do I need a will or a trust?

A. That depends  entirely upon your circumstances. State law  dictates how your
   property will pass in  the event that you do not have a  will. If you have a
   will or trust you can implement your more specific desires and you can do it
   more  comprehensively. There  is  a  current trend  toward  trusts (even  on
   smaller estates)  to avoid the  effort and  expense of probate,  to maintain
   privacy, to provide more flexibility and  to manage finances in the event of
   incapacity.

Q. I'm getting older. Should I add my  children's name to the deed for my house
   or farm?

A.  There  are  several  issues  involved  and  potential  problems  with  this
   arrangement,  including  possible  gift  and  estate  tax  implications  and
   Medicaid eligibility issues.  You will need the signatures of  the child and
   his or her spouse if you wish to sell or mortgage the property. Also, if the
   child  becomes  involved  with  creditors, tax  problems,  litigation  or  a
   divorce,  additional  problems  may  arise  which  cause  you  troubles  and
   expense. In some circumstances it is possible to lose the property.

Q. I am  thinking of making gifts to  my children, but I have heard  there is a
   tax on gifts. When does the tax apply?

A. A person can  give up to $15,000 per year per person  to an unlimited number
   of recipients  without gift tax.  Gifts over $15,000 in  a year to  a single
   donee are taxable gifts, for which a gift tax return must be filed.

Q. My  aunt's health  is failing  and she needs  someone to  help her  with her
   business. Can this be accomplished fairly easily?

A. Usually,  Yes. Assuming  your aunt  is still competent,  a durable  power of
   attorney may be executed, giving you  the authority to transact business for
   her. If  she's not  competent, you  may have to  consider going  through the
   courts to  establish a  conservatorship for her.  There are  also healthcare
   powers of attorney that would enable  you to help her with making healthcare
   decisions if she is unable. A trust may also be appropriate. These documents
   can be done  individually or in connection with a  more comprehensive estate
   plan. In any event, there are mechanisms that allow you to help her with her
   needs.

Q. My mother is failing noticeably, is it too late to do a will?

A. Probably not.  As long as she  knows the general nature of  her property and
   who she wants to receive it, she is likely still competent to execute estate
   planning documents. The test is not whether  she is still able to do her own
   business. It is important that  various formalities be followed in executing
   these documents, and it is particularly important with your mother's current
   health circumstances.

Q. I have  read that you should not  keep your original will in  a safe deposit
   box because nobody would have access to it if you die. Is this correct?

A. No. Kansas law provides that when the holder of a safe deposit box dies, the
   bank may open the box in the presence  of those who claim an interest in the
   contents and remove any will for delivery to the court. The bank should also
   allow  you  to remove  life  insurance  policies  and  deliver them  to  the
   beneficiaries.  The remainder  of  the  contents can  be  removed after  the
   executor of the estate is appointed.

Q. I have a durable power of attorney. Do I also need a will?

A. A durable  power of attorney allows  someone you appoint to  do business for
   you while you are alive. Legally,  the authorization contained in a power of
   attorney ceases at death. A will is one of the several ways to pass property
   to your  beneficiaries at  your death. A  will has nothing  to do  with your
   property  while you  are alive.  The  answer to  your question  is that  you
   probably  need both  a power  of attorney  and a  will. These  documents are
   normally part of  a coordinated estate plan that all  persons should have in
   place.

Q. Is there a  difference between a Durable Power of  Attorney and a Healthcare
   Power of Attorney?

A. Yes. A Durable Power of Attorney generally applies to business and financial
   matters  only. Without  this  document a  court-ordered conservatorship  may
   become  necessary  in the  event  of  incompetency.  A Healthcare  Power  of
   Attorney, as the name implies,  refers to healthcare matters like consenting
   to  medical   procedures,  making   living  arrangements  and   things  like
   that.  Without  this  document,  a  court-ordered  guardianship  may  become
   necessary  in the  event of  incompetency.  A coordinated  estate plan  will
   normally include both of these powers  of attorney because they do different
   things.
*** No, You Don't Need a Simple Will
:PROPERTIES:
:cite:     http://www.bostonlegacylaw.com/no-you-dont-need-a-simple-will/
:author:   William F. Coyne, Jr.
:produced-by: Boston Legacy Planning
:END:

Over the  years, many people  have told  me, at an  early stage in  our initial
meeting: “I need a  simple will,” or sometimes, “I just need  a simple will.” I
have proceeded on the assumption, usually proven correct, that they had no idea
what a simple will does or does  not do, and that their statement translates to
“I’m not going  to pay a lot for  this muffler!” So I would  usually ignore the
statement, and go on to my questions about their concerns.

But I sometimes  wonder if our relationship  would have gotten off  to a better
start if  I had been  more direct in my  response. The conversation  might have
gone something like this.

“I need a simple will.”

“That’s really unlikely”

“Huh?”

“Well,  unless you  are playing  scavenger  hunt, and  your list  of things  to
collect includes a simple will, you probably don’t need a simple will.  But let
me ask you a few questions to make sure. How do you feel about probate?”

“Not so  good. I  had an  aunt whose estate  went through  probate, and  it was
pretty awful.”

“If you were to become mentally incapacitated, would you want some control over
who was in  charge of your affairs, how  the money was spent, and  how you were
taken care of?

“You bet.”

“When  you leave  property  to your  kids,  would  you like  that  money to  be
protected in case they get sued, or go through a divorce?

“Absolutely.”

“Well then, you don’t  need a simple will. What you need  is a revocable living
trust.”

Time out. Note that I have not yet  asked how much money is involved, or raised
the  specter of  estate taxes.  People often  have the  mistaken idea  that the
trust v. will question is a matter of  how much money they have. The reality is
that the benefits of trusts are most important in smaller estates. For example,
is it more important to protect  a child’s inheritance when the amount received
is $200,000 or $200  Million?  If you think about it, it is  easy to see that a
$300,000 judgment is  a drop in the bucket  in one case, and a  disaster in the
other.  And why should only the super  wealthy have the ability to control what
happens to them if dementia strikes?

If I had determined that a married couple had total assets – including value of
the house, and face  value of all insurance policies –  of more than $1Million,
then the Massachusetts estate tax would be an issue, and there would be all the
more reason for an  RLT. For business owners, or for  couples with total assets
of over  $2 Million, the trust  is clearly the  better way to proceed.  Still I
have found that  even some people with significant assets  think that they just
need a simple will. It seems to be more a matter of lack of information than of
net worth. But let’s continue with our conversation from where we took the time
out.

“Well then, you don’t  need a simple will. What you need  is a revocable living
trust.”

“How much will that cost?”

“Probably  more than  you  want  to pay.  But  now at  least  we  are having  a
conversation about the real  issue — not what you need, but  what the cost will
be. So let’s have that conversation.”
** Fiduciaries
*** Lawyers as Trustees
:PROPERTIES:
:cite:     https://actecfoundation.org/podcasts/lawyers-as-trustee-risks-ethics/
:author:   Steven A. Benenfield
:date:     May 2019
:produced-by: The American College of Trust and Estate Counsel, ACTEC
:END:
“Lawyers as  Trustees,” that’s the  subject of  today’s ACTEC Trust  and Estate
Talk.   Transcript/Show  Notes   This  is  Susan  Snyder,   ACTEC  Fellow  from
Chicago. As  trust and estate  planning lawyers,  we are often  confronted with
client requests  that benefit  the client  by reducing the  cost of  current or
future representation,  providing first-hand knowledge and  efficient execution
of his or her intentions by a trusted disinterested advisor, and filling a role
for  which a  client has  no  other appropriate  choice or  being the  client’s
long-term  informal general  counsel  or family  lawyer.  Because the  client’s
request could also benefit the attorney,  how can the attorney sort through the
ethical and legal conflicts and obligations? To address these issues, you’ll be
hearing   today  from   ACTEC   Fellow,  Steven   Benefield  from   Birmingham,
Alabama.  Welcome, Stephen.

Thank you, Susan,  it’s a pleasure to be  here today. I’d like to zero  in on a
topic  of  particular interest  to  lawyers  who  draft  wills and  trusts  for
clients. We  frequently have clients who  come to us  who say they have  no one
else to  serve as their executor  or the trustee  of their trust, and  they ask
their lawyer to fill that role. And  there are many reasons that a lawyer might
or might  not do  that. For  instance, the  drafting lawyer  might be  the best
person to serve as the trustee in the client’s will or trust because the lawyer
knows  the terms  of the  will and  trust better,  probably, than  anyone else,
including the client.   The lawyer’s legal and ethical  training, and knowledge
and expertise can provide added value  to the client and particularly where you
have long-standing relationships with a client, you may be familiar with family
dynamics and  conflicts and who  can be trusted and  who can’t be  trusted much
better than anyone, sometimes any other  family member even.

Now, the issue  is where you get down  to where you normally have  an issue and
that is money. And when the lawyer is  going to get paid for these services, it
raises a  number of ethical  and legal questions  that can result  in potential
liability for lawyers.  The issue of what a lawyer gets paid, how much they get
paid, and  what they do  for what they get  paid, particularly as  the executor
under will  or the trustee of  the trust, has been  the subject of a  number of
written documents over a  number of years.

The first, if you go back to 1973, the American Bar Association Section on Real
Property, Probate and Trust issued  a statement of principles regarding probate
practices and  expenses that dealt specifically  with the issue of  lawyers who
served as the guardian  of a person or is the executor under  a will and took a
fee not only as the executor or the guardian, but also a fee for serving as the
lawyer for the executor or the guardian because those are actually two separate
roles.  There was some  perception that there had been some  abuse in that area
and  so the  ABA, the  American  Bar Association,  came out  with some  written
guidance for  lawyers on  that. In  1992, the  same ABA  section came  out with
Principles for Attorneys Acting in Other  Fiduciary Roles, and in 1994 that was
also published  in a special  report of that section.

Come along  to 2002 and  Rule 1.8 of the  Model Rules of  Professional Conduct,
which  deal with  prohibited  transactions for  lawyers  and specifically  with
transactions between lawyers and clients and  when there is an exception to the
absolute bar  of those transactions, added  comment Number 8 to  Rule 1.8 which
essentially says that Rule 1.8 doesn’t apply to the situation in which a client
and the client’s lawyer, who is drafting a  will or trust, ask the lawyer to be
the fiduciary  under that document.   So that’s not considered  a “transaction”
between lawyer and the client.

Now, understand that the Rules of Professional Conduct, which have been adopted
in most states,  although not in any  state without some changes  and with many
states a lot of  changes; California to the point you  might not recognize them
and a  few other  states as  well, are only  for lawyer  disciplinary purposes.
These are the rules  that the bar association and the  courts used to determine
whether  lawyers keep  their  license to  practice law,  whether  they will  be
suspended or  disbarred or reprimanded for  actions that they take  as lawyers.
Many of the rules follow and come  from the fiduciary duties that apply between
a principal and an  agent. Attorneys in one sense are  nothing more than agents
for  their clients  as  principals and  as  agents we  are  fiduciaries to  our
clients.  As  such, we  have fiduciary duties  to our clients  and in  order to
fulfill those duties and to help lawyers  in part remember them, learn them and
keep them sort of  at the forefront, many of the  Rules of Professional Conduct
restate fiduciary  duties that lawyers  owe to  their clients.  In  some cases,
they are  actually much more  specific than  the general fiduciary  duties that
apply between a principal and agent.

For instance, the Rule on Confidentiality that applies to a lawyer is extremely
broad. It  applies to any  information about the client,  including information
that is  gained from  a public  source.  As  lawyers, we  don’t talk  about our
clients to anyone about anything unless it is to pursue the representation.  It
doesn’t matter that there was an article  in the newspaper about our client. We
don’t get to talk  about it. So, in that sense, the  duty of confidentiality is
far broader than  that of your typical agent in  a principal agent relationship
or the duty of a trustee in your  typical express trust, which is the basis for
defining fiduciary duties  as we generally understand them, and  if you look to
the  Restatement of  the Law  of Trusts  and read  it in  conjunction with  the
Restatement of the Law Governing Lawyers, you will find there’s a great deal of
overlap and cross-reference  between the two.

So, what do  we do about finding  ways to do this? States  have taken different
approaches  in whether  lawyers  can agree  to  serve as  a  fiduciary under  a
document that’s  drafted by the  lawyer. Some states in  the past have  taken a
very  dim view  of that.  Other states  such as  California and  New York  have
statutes that  expressly permit  lawyers to serve  as fiduciaries  in documents
they draft.  In some states, such as Georgia, courts have adopted express rules
and procedures that  need to be followed.   And then, under the  Model Rules as
adopted in most states, we have the  rules on Conflicts of Interest in Rule 1.7
and Rule 1.8,  coupled with the rules governing communications  with the client
and the concept of informed consent by  the client to the representation and to
the additional role that’s being taken  on as the fiduciary under the document.
And of course,  the concept of informed consent requires  that a lawyer explain
in  some  detail  the  potential  risk  and the  advantages,  as  well  as  the
alternatives to the proposed course of action.   So that if the client is going
to ask you to be the trustee  or executor, then it’s the lawyer’s obligation to
explain that  there are  other ways  that can be  accomplished; that  there are
institutions who  will serve as  fiduciary; that  there are family  members who
might  serve as  fiduciaries.  In  some states  and  other  pockets, there  are
individuals  who serve  as professional  fiduciaries who  are not  lawyers. And
that’s perfectly okay, if  they’re willing to take that on.

So, what are some of the things you need to worry about if you are a lawyer who
is going to accept the appointment as the executor or trustee?  To the extent
that some states still have what we used to refer to as the Model Code of
Professional Responsibility, there was an ethical consideration that dealt with
this issue directly, which simply said that a lawyer should not consciously
influence a client to name him or her as the executor or trustee under a
document that that lawyer drafts.  Now, that rule was criticized as being
fairly vague, but I think that criticism might actually have been a bit
overblown because one could argue that many of the general fiduciary duties
that any fiduciary owes, whether it’s the agent to a principal or the trustee
of the express trust, or a lawyer to a client, are going to be vague.

For instance, in Rule 1.7 of the  Rules of the “Rules of Professional Conduct,”
which are used as the minimum  standard for lawyer discipline, 1.7(b) says, you
shall not  take representation  or maintain representation  to the  extent that
there is  a significant risk that  your representation of someone  else or your
personal interest might  materially limit your representation.   Well, just how
vague is a  significant risk and a material limitation  on your representation?
Well, it’s kind of  like, equity is as long as the  Chancellor’s big toe.  What
is significant to you might not be too significant to me and what is a material
limitation  might  seem  insignificant  to   me.   So,  there  you  go.   Don’t
necessarily throw things out as vague simply because they are broad.

Comment 8 to Rule  1.8 that I mentioned earlier says that, if  you are going to
be the executor or trustee for your  client, then you don’t have to worry about
jumping  through  all of  the  hoops  that come  with  engaging  in a  business
transaction  with your  lawyer, and  those  hoops include  encouraging, if  not
demanding, that your  client gets separate legal representation,  and taking an
objective  view to  the  representation  from the  client’s  perspective as  to
whether it is  reasonable and fair. Well, once again,  what’s reasonable is the
subject of a  great deal of litigation,  and as we all know,  fair is something
that occurs in the fall.

So, if you can figure that out just  from the typeface of the rule, you will be
in better shape than I am.  In any event, the American Bar Association in 2002,
shortly before Comment  8 came out for Rule 1.8,  issued Formal Opinion 02–246,
just three months before the Comment 8  out, and it concluded that not only was
it okay for a lawyer to be named  as the fiduciary under the will or trust that
the lawyer is  drafting, but the representations and the  disclosures that were
required  were a  good deal  less expansive  than what  some commentators  have
suggested are required.

For  one thing,  the concept  of informed  consent that  I mentioned,  is about
disclosing information to your client and Formal Opinion 02-246 speaks in terms
of  what is  disclosed to  the client.   Well, Professor  Rounds in  Loring and
Rounds: A  Trustee’s Handbook suggests that  that doesn’t go quite  far enough,
because from a malpractice or  professional liability standpoint or a fiduciary
duty standpoint,  which is what governs  our relationship with our  client, not
the Rules of Professional Conduct. The Rules of Professional Conduct govern our
relationship with  the bar association and  the court. The law,  the civil law,
governs  our relationship  between our  clients and  ourselves and  that’s what
determines  whether we  end  up  owing our  clients  money  because we’ve  done
something to damage their interest and we  get sued and it goes to court. Well,
we can talk about that in many  ways, but the simple fact is, the understanding
that the client has to have is the  key.  It’s not what we tell them, it’s what
they understand.

And so if you are going to be the trustee or the executor under a will or trust
that you  draft for  a client,  it’s critical  that you  make sure  that client
understands and you have done everything in your power to make sure that client
understands and that you can prove it. Now, there are other problems with being
a  trustee  for  a client,  not  the  least  of  which  is that  the  Rules  of
Professional Conduct apply  a standard of care that probably  sets the standard
of care for civil liability and holds lawyers to be professional trustees.  And
if you want  to look at some  of the obligations of  the professional trustees,
then go to  the website for the  Office of the Comptroller of  the Currency and
see what the obligations of banks and other lending institutions are, that have
trust departments, with respect to  serving as trustees.  They are professional
trustees. And you  might say, “well, I’m  just a single individual. I  am not a
bank.  I don’t have to be powered by that standard.” Well, let me know how that
works out for you. Because as far as  I know, the fiduciary duty doesn’t make a
distinction between  degree.  You are  either a professional trustee  or you’re
not. So  there’s the caution  for the day:  if you want to  be a trustee  or an
executor  under a  document that  you are  drafting for  a client,  beware.  Be
careful what  you ask  for, because you  may get more  than you  bargained for.


Great.  Thanks, Steven.  Thanks for  helping us through this ethical minefield.

Thank you.

* Areas of Practice
- Estate Planning,
  - Base planning
    - Revocable Living Trusts,
    - Wills,
    - Powers of Attorney,
    - Health Care Documents
  - Advanced Planning
    - Plan design,
    - implementation and management services to achieve lifetime financial goals,
    - avoid income and estate taxes, and
    - optimize integrated planning strategies.

- Legacy Planning

  There are many ways  to think of legacy planning.  One  aspect is that legacy
  planning “estate planning  for people who have a story  to tell.” It involves
  capturing and passing on family stories, wisdom earned from life experiences,
  values, hopes and  treasured personal possessions.  That  deeper knowledge of
  life’s goals can impact the entire estate plan in profound ways.

- Business Transition Planning
  - Business exit planning
  - Business succession planning
  - Planning for multi-owner businesses

- Asset Protection Planning
  - Comprehensive Asset Protection Audit™
  - Creation of
    - trusts,
    - LLCs,
    - series LLCs,
    - domestic asset protection trusts
    - Ongoing maintenance of asset protection entities

- Dispute Avoidance and Resolution
  - Alternative Dispute Resolution systems design for corporations, LLCs and trusts
  - Mediation and facilitation services
  - Collaborative law and settlement counsel
  - Litigation of trust and estate disputes
  - Appeals in trust and related areas

- the Avoidance and Resolution of Disputes Involving
  - trusts,
  - estates,
  - business owners and
  - fiduciaries.

- Trust and Estate Settlement
  - Probate and trust settlements
  - Postmortem planning
  - Beneficiary trust design and maintenance

* Build Tools
:PROPERTIES:
:appendix: t
:custom_id: build-tools
:END:
** Makefile					:dependencies:env_vars:perl:
:PROPERTIES:
:appendix: t
:dependency1: make
:dependency2.0: AWS User account at https://aws.amazon.com
:dependency2.1: AWS cli v2 in PATH https://docs.aws.amazon.com/cli/index.html
:dependency2.2: See how to Install AWS CLI v2 at https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html
:dependency2.3: aws credentials: access token and secret access token stored in ~/.aws/credentials
:dependency2.4: AWS S3 buckets set up for serving a static web page
:dependency3: GitHub Account with personal access token stored in GITHUB_TOKEN
:dependency4: texinfo @6.7._
:dependency5: Emacs, Org-mode, Babel language 'shell' enabled
:env_var1: SYNC_ORG_TEMPLATE: holds the full path to this Template.org file
:env_var2: GITHUB_TOKEN: holds the GitHub personal access token
:env_var3: EDITOR: must hold a reference to a working emacsclient server
:env_var4: COLORS
:END:

#+name:Makefile
#+header: :tangle Makefile
#+begin_src makefile

  ###############################################################################
  ### USER-DEPENDENT VARIABLES
  ### USE ENVIRONMENT VARIABLES WHENEVER POSSIBLE

  # NOTE: All environment variables need to be exported PRIOR to starting the
  # Emacs server as EDITOR in your shell startup files; otherwise, they will not
  # be available to Emacs.
  # When I moved from using Bash to Zsh, I inadvertently changed the order of
  # import, and started the Emacs server before importing, and caused a horrible
  # bug which caused the program to work on one computer but fail on another.

  # The absolute path to this Template file
  TEMPLATE := $(SYNC_ORG_TEMPLATE)


  ### TOOLS & RESOURCES
  # tools is a directory holding tangled scripts, such as cmprpl
  # resources is a directory holding static resources for the project
  # images is a directory holding jpg and png image files
  RESOURCES 	:= resources
  TOOLS		:= $(RESOURCES)/tools
  IMAGES	:= $(RESOURCES)/images
  CMPRPL	:= $(TOOLS)/cmprpl

  # Use emacsclient as $EDITOR; make sure it is set in a shell startup file and
  # the server has been started.
  EMACS		:= $(EMACS)
  EDITOR	:= $(EDITOR)

  # User’s personal GitHub token for authentication to GitHub
  # DO NOT HARD-CODE THIS VALUE
  GITHUB_TOKEN	:= $(GITHUB_TOKEN)

  # The AWS Command Line Interface (AWS CLI) is an open source tool
  # that enables you to interact with AWS services using commands in
  # your command-line shell.  It must be present on your system.  Run the 'make'
  # command 'install-aws-cli' to install it if you do not have it.  Be sure to
  # run 'aws configure' after installing it.  This will place your AWS
  # credentials into ~/.aws/credentials.
  AWS	:= aws
  S3	:= $(AWS) s3
  CF	:= $(AWS) cloudfront
  CFD	:= $(CF) list-distributions

  ### END OF USER-DEPENDENT VARIABLES
  ###############################################################################
  ### MAKE-GENERATED VARIABLES

  ### PROJ AND ORG
  # ORG is the name of this Org file with extension .org
  # PROJ is the project name---the Org file name without extension.

  ### NOTE: there can be only one Org file in the project directory;
  # so far this has not been a problem, but it might be.

  PWD  := $(shell pwd)
  ORG  := $(shell ls *.org)
  PROJ := $(basename $(ORG))

  ### NOTE: S is needed only for the Template file because of the way it
  # is nested  one level deep in  the Templates GitHub repo,  which uses
  # the plural  form of Templates,  whereas this file uses  the singular
  # form,  Template. So  when the  homepage  link is  updated, the  curl
  # command must  be told to  use the plural  form. This is  obviously a
  # hack only  for my own use  and can be  removed once I clean  up this
  # anomaly.

  ifeq ($(PROJ),$(basename $(notdir $(TEMPLATE))))
	  S := s
  endif

  # The AWS S3 bucket to use to  store the html source file; it is found
  # at the  key #+bucket towards  the beginning  of the file  and should
  # include the appropriate suffix (.com, .net, .org, etc)
  BUCKET       := $(shell $(EDITOR) --eval \
		 '(with-current-buffer (find-file-noselect "$(ORG)") \
		    (save-excursion \
		      (goto-char (point-min)) \
		      (re-search-forward "^\#[+]bucket:\\(.*\\)$$" nil t) \
		      (match-string-no-properties 1)))')
  S3_BUCKET    := s3://$(BUCKET)

  # Buckets set up to serve static web sites from S3 can use either http
  # or https protocols; some  http protocols will automatically redirect
  # to https;  however, some only use  http. I would like  to accomodate
  # both, and  so this code  finds the url's  that are in  my Cloudfront
  # account, which presumably will serve https.  If the url is not here,
  # then this must be set up to serve http instead.
  HTTP_S := $(shell $(CFD) | perl -MJSON::PP -e \
	  '$$/=""; \
	   my @urls = (); \
	   my $$json=JSON::PP->new->decode(<STDIN>); \
	   for my $$item ( @{$$json->{"DistributionList"}{"Items"}} ) { \
		  push @urls, @{$$item->{"Aliases"}{"Items"}}; \
	   } \
	  my $$found = grep { /'$(BUCKET)'/ } @urls; \
	  print "http", ($$found ? "s" : "");')

  HTTP_S_BUCKET := $(HTTP_S)://$(BUCKET)

  ### DIR, SRC

  # DIR is  the .info name found  at '#+texinfo_filename:<DIR>.info' (at
  # the  bottom  of this  file  in  the export  configuration  settings)
  # without its extension, used as the INFO filename and the name of the
  # HTML export  directory; this code  uses the lowercased PROJ  name if
  # there is no '#+texinfo_filename'.

  # SRC is HTML directory based upon the DIR name

  #DIR := $(shell $(EDITOR) --eval \
  #	'(with-current-buffer (find-file-noselect "$(ORG)") \
  #		(save-excursion \
  #		(goto-char (point-min)) \
  #		(re-search-forward "^\#[+]\\(?:texinfo_filename\\|TEXINFO_FILENAME\\):\\(.*\\).info$$" nil t) \
  #		(match-string-no-properties 1)))')

  DIR := $(shell sed -E -n "/^\#\+texinfo_filename/s/^.*:(.*)\.info$$/\1/p" $(ORG))
  ifeq ($(DIR),$(EMPTY))
	  DIR := $(shell echo $(PROJ) | tr "[:upper:]" "[:lower:]")
  endif

  SRC := $(DIR)/

  ### VERS: v1.2.34/
  # VERS is the version number of this Org document.
  # When sync is run after the version number has been updated, then VERS
  # picks up the newly-changed value.  VERS used to be staticly imbedded
  # when the Makefile was tangled, but it needs to be dynamic for
  # development.

  # QUERY: should this number be formatted like this, or should it be just the numbers?
  # The reason it includes them is the S3PROJ obtains the name from the S3 bucket, and
  # it includes them.  But it only includes them because I have made it so.  Not a good
  # reason just by itself.  The ending slash is not actually a part of the version, but
  # comes from the way the 'aws2 ls' command returns its values.	So VERS should probably
  # not include the trailing slash, although it doesn’t hurt anything.

  VERS := v$(shell $(EDITOR) --eval \
	  '(with-current-buffer (find-file-noselect "$(ORG)") \
		  (save-excursion \
		    (goto-char (point-min)) \
		    (re-search-forward "^\#[+]\\(?:macro\\|MACRO\\):version Version \\(\\(?:[[:digit:]]+[.]?\\)\\{3\\}\\)") \
		    (match-string-no-properties 1)))')/

  ### AWS
  # PROJ_LIST contains the list of projects currently uploaded to
  # the S3 bucket; each item contains the name of the project and its
  # current version.

  # Created function using elisp instead of the shell.
  # This variable contains an elisp list of strings of the form '("proj1-v1.2.3/" "proj2-v4.5.6/" ...)'
  # However, when it prints to the shell, the quotes are lost.
  # Need to make sure elisp's variable 'exec-path contains the proper $PATH instead of adding to 'exec-path.

  PROJ_LIST := $(shell $(EDITOR) --eval \
	  "(progn \
		  (require (quote seq)) (add-to-list (quote exec-path) (quote \"/usr/local/bin\")) \
		  (seq-map (lambda (s) (replace-regexp-in-string \"^\s+PRE \" \"\" s)) \
			  (seq-filter (lambda (s) (string-match-p (regexp-quote \" PRE \") s)) \
			  (process-lines \"$(AWS)\" \"s3\" \"ls\" \"$(S3_BUCKET)\"))))")

  ### S3PROJ
  # The name of the current project as obtained from S3: 'proj-v1.2.34/'
  # If there is no current project in the S3 bucket, then assign a value equal to
  # the Org project and version instead.  It is set to the project if found, and
  # NO if not found, then updated in the ifeq block below.
  S3PROJ := $(shell $(EDITOR) --eval \
		  '(let ((proj (seq-find (lambda (s) (string-match-p "$(DIR)" s)) (quote $(PROJ_LIST))))) \
		     (or proj (quote NO)))')

  ### PROJINS3
  # is used by make sync; this allows the index.html file to be generated the first
  # time the project is synced.  It is set to NO if this project is not currently in an
  # S3 bucket, and it is set to YES if it is.
  PROJINS3 :=

  ### S3VERS
  # The version of this project currently installed in the S3 bucket: 'v1.2.34/'
  # If there is no current version in the S3 bucket, then assign the version from
  # this Org file instead.
  S3VERS   :=

  # Update S3PROJ, S3VERS, and PROJINS3
  ifeq ($(S3PROJ), NO)
	  S3PROJ := $(DIR)-$(VERS)
	  S3VERS := $(VERS)
	  PROJINS3 := NO
  else
	  S3VERS := $(subst $(DIR)-,,$(S3PROJ))
	  PROJINS3 := YES
  endif

  ### GITHUB
  # USER is the current user's GitHub login name.

  # The user name used to be statically embedded into the Makefile
  # during tangle, but in an effort to make the Makefile dynamically
  # indepedent, dynamic code has replaced the static code.  The code
  # that placed the static name in the Makefile was a 'node' script that
  # ran in a separate Org process during tangle.	An unfortunate fact of
  # 'make' is that 'make' strips the quote marks from the string
  # obtained from the 'curl' command when the 'make shell' command
  # returns the string.	 This makes the string malformed JSON and
  # unparsable by most JSON parsers, including 'node’.	However,
  # 'perl'’s core module JSON::PP (but not JSON::XS) has facilities to
  # parse very malformed JSON strings.	Therefore, this dynamic code
  # uses 'perl' and the core module JSON::PP to parse the 'curl' string
  # into a 'perl' JSON object which can return the login name.	This
  # code should work with any version of 'perl' without having to
  # install any modules.

  USER	:= $(shell \
	    curl -sH "Authorization: token $(GITHUB_TOKEN)" https://api.github.com/user \
	    | \
	    perl -MJSON::PP -e \
		'$$/ = ""; \
		 my $$json = JSON::PP->new->loose->allow_barekey->decode(<STDIN>); \
		 print $$json->{login};' \
	    )
  SAVE		:= resources

  ### TEXINFO
  TEXI		:= $(PROJ).texi
  INFO		:= $(DIR).info
  INFOTN	:= $(shell $(EDITOR) --eval "(file-truename \"$(INFO)\")")
  PDF		:= $(PROJ).pdf
  INDEX		:= index.html
  HTML		:= $(DIR)/$(INDEX)
  DIR_OLD	:= $(DIR)-old

  ### AWS S3
  DST_OLD	:= $(S3_BUCKET)/$(S3PROJ)
  DST_NEW	:= $(S3_BUCKET)/$(DIR)-$(VERS)
  EXCL_INCL	:= --exclude \* --include \*.html
  INCL_IMAGES	:= --exclude \* --include \*.jpg --include \*.png
  GRANTS	:= --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
  S3SYNC	:= $(S3) sync --delete $(EXCL_INCL) $(SRC) $(DST_OLD) $(GRANTS)
  S3MOVE	:= $(S3) mv --recursive $(DST_OLD) $(DST_NEW) $(GRANTS)
  S3COPY	:= $(S3) cp $(INDEX) $(S3_BUCKET) $(GRANTS)
  S3REMOVE	:= $(S3) rm $(S3_BUCKET)/$(S3PROJ) --recursive
  S3IMAGESYNC	:= $(S3) sync $(INCL_IMAGES) $(IMAGES) $(S3_BUCKET)/$(IMAGES) $(GRANTS)

  ###############################################################################

  default: check texi info html pdf

  PHONY: default all check values boot \
	    texi info html pdf \
	    open-org open-texi open-html open-pdf \
	    clean dist-clean wiped-clean \
	    help sync update delete-proj \
	    install-aws-cli \
	    index-html upload-index-html

  values: check
	    @printf "$${BLUE}Values...$${CLEAR}\n"
	    @echo TEMPLATE:	$(TEMPLATE)
	    @echo EDITOR:	$(EDITOR)
	    @echo USER:		$(USER)
	    @echo PWD:		$(PWD)
	    @echo PROJ:		$(PROJ) $S
	    @echo ORG:		$(ORG)
	    @echo TEXI:		$(TEXI)
	    @echo INFO:		$(INFO)
	    @ECHO INFOTN:	$(INFOTN)
	    @echo BUCKET:	$(BUCKET)
	    @echo S3_BUCKET:	$(S3_BUCKET)
	    @echo HTTP_S:	$(HTTP_S)
	    @echo HTTP_S_BUCKET:$(HTTP_S_BUCKET)
	    @echo VERS:		$(VERS)
	    @echo S3PROJ:	$(S3PROJ)
	    @echo S3VERS:	$(S3VERS)
	    @echo DIR:		$(DIR)
	    @echo DIR_OLD:	$(DIR_OLD)
	    @echo SRC:		$(SRC)
	    @echo DST_OLD:	$(DST_OLD)
	    @echo DST_NEW:	$(DST_NEW)
	    @echo PROJ_LIST:	"$(PROJ_LIST)"
	    @echo PROJINS3:	$(PROJINS3)

  check:
	    @printf "$${BLUE}Checking dependencies...$${CLEAR}\n"

	    @[[ -z $(BUCKET) ]] && \
	       { printf "$${RED}$(BUCKET) $${CYAN}must be set.$${CLEAR}\n"; exit 1; } || \
	       printf "$${CYAN}BUCKET: $${GREEN}$(BUCKET)$${CLEAR}\n";

	    @[[ -z $${GITHUB_TOKEN} ]] && \
	       { printf "$${RED}GITHUB_TOKEN $${CYAN}must be set.$${CLEAR}\n"; exit 1; } || \
	       printf "$${CYAN}GITHUB_TOKEN: $${GREEN}SET$${CLEAR}\n";

	    @[[ (-d ~/.aws) && (-f ~/.aws/credentials) && (-f ~/.aws/config) ]] && \
	       printf "$${CYAN}AWS credentials and config: $${GREEN}SET$${CLEAR}\n" || \
	       { printf "$${RED}~/.aws 'credentials' and 'config' must be set.$${CLEAR}\n"; exit 1; }

	    @[[ "$(shell $(EDITOR) --eval '(member (quote texinfo) org-export-backends)')" = "(texinfo)" ]] && \
		  printf "$${CYAN}Texinfo backend: $${GREEN}INSTALLED.$${CLEAR}\n" || \
		  { printf "$${YELLOW}Texinfo backend:$${CLEAR} $${RED}NOT INSTALLED; it must be installed.$${CLEAR}\n"; exit 1; }

	    @[[ $(shell $(EDITOR) --eval '(symbol-value org-confirm-babel-evaluate)') == "t" ]] && \
		  { printf "$${YELLOW}org-confirm-babel-evaluate:$${CLEAR} $${RED}T; set to NIL.$${CLEAR}\n"; exit 1; } || \
		  printf "$${CYAN}org-confirm-babel-evaluate: $${GREEN}OFF.$${CLEAR}\n\n"

  open-org: $(ORG)
	    @$(EDITOR) -n $(ORG)
  $(ORG):
	    @echo 'THERE IS NO $(ORG) FILE!!!'
	    exit 1

  texi: $(TEXI)
  $(TEXI): $(ORG)
	   @echo Making TEXI...
	   @$(EDITOR) -u --eval \
		  "(with-current-buffer (find-file-noselect \"$(ORG)\" t) \
			  (save-excursion \
			  (org-texinfo-export-to-texinfo)))"
	   @echo Done making TEXI.
  open-texi: texi
	   @$(EDITOR) -n $(TEXI)

  info: $(INFO)
  $(INFO): $(TEXI)
	   @echo Making INFO...
	   @makeinfo -o $(INFO) $(TEXI)
	   @$(EDITOR) -u -eval \
		  "(when (get-buffer \"$(INFO)\") \
			  (with-current-buffer (get-buffer \"$(INFO)\") \
				  (revert-buffer t t t)))"
	   @echo Done making INFO.

  open-info: info
	   @$(EDITOR) -u -eval \
		  "(if (get-buffer \"*info*\") \
			  (with-current-buffer (get-buffer \"*info*\") \
				(when (not (string= \"(symbol-value (quote Info-current-file))\" \"$(INFOTN)\")) \
					(info \"$(INFOTN)\")) \
				(revert-buffer t t t)) \
		      (info \"$(INFOTN)\"))"

  html: $(HTML)
  $(HTML): $(TEXI)
	   @echo Making HTML INFO..
	   @makeinfo --html -o $(DIR) $(TEXI)
	   @echo Done making HTML.
	   $(CMPRPL) $(DIR) $(DIR_OLD)
  open-html: html
	   @open $(HTML)

  # If pdftexi2dvi produces an error, it may still produce a viable PDF;
  # therefore, use --tidy.  If it produces an error, try to link the PDF;
  # if it does not produce an error, the PDF will be added to the top dir
  # and there will be no attempt to link.
  pdf:	$(PDF)
  $(PDF): $(TEXI)
	  @echo Making PDF INFO...
	  @-pdftexi2dvi --quiet --build=tidy $(TEXI) || ln -s $(PROJ).t2d/pdf/build/$(PDF) $(PDF)
	  @echo Done making PDF.
  open-pdf:pdf
	   @open $(PDF)

  sync:   $(HTML)
	  @echo Syncing version $(VERS) onto $(S3VERS)...
	  $(S3SYNC)
	  $(S3IMAGESYNC)
	  @echo Done syncing.
	  [[ $(VERS) != $(S3VERS) ]] && { echo Moving...; $(S3MOVE); echo Done moving.;  make homepage; } || :
	  [[ $(PROJINS3) = "NO" ]] && make homepage || :

  # This is a target-specific variable for updating the “description”
  # key on the GitHub repo page with the current version number.  It
  # first makes a curl call to the GitHub project repo, finds the
  # “description” line, pulls out the description only (leaving the old
  # version) and then prints the value with the current version number.
  # This value is used by the “homepage:” target in the PATCH call.
  # This method is arguably harder to code but faster to run than using
  # Perl with the JSON::PP module.

  homepage: description = $(shell \
	  curl -s \
		  -H "Authorization: token $(GITHUB_TOKEN)" \
		  https://api.github.com/repos/$(USER)/$(PROJ)$S | \
		  (perl -ne 'if (/^\s*\"description\":\s*\"(.*): v(?:(?:[[:digit:]]+[.]?){3})/) {print $$1}'))

  ### NOTE the use of the S variable at the end of PROJ; this is to handle
  # the singular case of the GitHub repo using the plural form, Templates
  # whereas the the Template.org file uses the singular form.
  homepage: $(ORG) upload-index-html
	    @echo Updating homepage...
	    @echo DESCRIPTION: $(description)
	    @echo VERS: $(VERS)
	    @curl -i \
		  -H "Authorization: token $(GITHUB_TOKEN)" \
		  -H "Content-Type: application/json" \
		  -X PATCH \
		  -d "{\"homepage\":\"$(HTTP_S_BUCKET)/$(DIR)-$(VERS)\",\
		       \"description\":\"$(description): $(VERS)\"}" \
		  https://api.github.com/repos/$(USER)/$(PROJ)$S
	    @echo Done updating homepage.

  delete-proj:
	  @echo Deleting project $(PROJ)...
	  @curl -i \
		  -H "Authorization: token $(GITHUB_TOKEN)" \
		  -H "Accept: application/vnd.github.v3+json" \
		  -X DELETE \
		  https://api.github.com/repos/$(USER)/$(PROJ)$S
	  @$(S3REMOVE)
	  @make dist-clean
	  @make upload-index-html
	  @$(EDITOR) -u --eval "(kill-buffer \"$(ORG)\")"
	  @rm -rf "../$(PROJ)"
	  @echo Done deleting project.

  index-html: $(INDEX)
  $(INDEX): $(ORG)
	  @echo making index.html...
	  $(EDITOR) --eval \
	  "(with-current-buffer (find-file-noselect \"$(ORG)\") \
		  (save-excursion \
		    (org-link-search \"#project-index-title\") \
		    (org-export-to-file (quote html) \"index.html\" nil t)))"
	  @echo Done making index.html.

  upload-index-html: $(INDEX)
	   @echo Uploading index.html...
	   $(S3COPY)
	   @echo Done uploading index.html

  install-aws-cli:
	    curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg" && \
	    sudo installer -pkg AWSCLIV2.pkg -target / && \
	    which aws && aws --version
	    rm -rf AWSCLIV2.pkg

  clean:
	  @echo Cleaning...
	    -@rm *~ 2>/dev/null
	    -@for file in *.??*; \
	    do \
		    ext=$${file#$(PROJ).}; \
		    [[ ! $${ext} =~ org|texi|info|pdf|html ]] && rm -rv $${file}; \
	    done

  dist-clean: clean
	  @echo Dist Cleaning...
	    @${EDITOR} -u --eval \
	      "(kill-buffer \"$(ORG)\")"
	    -@rm -rf *.{texi*,info*,html*,pdf*} $(DIR) $(TOOLS)
	    -@for dir in *; \
		do \
		    [ -d $$dir -a $$dir != "$(DIR_OLD)" -a $$dir != $(SAVE) ] && \
		    rm -vr $$dir; \
		done

  wipe-clean: dist-clean
	  @echo Wipe Clean...
	    -@rm -rf Makefile Readme.md $(DIR_OLD)
	    @git checkout Makefile README.md

  git-ready: dist-clean
	    git checkout Makefile
	    git checkout README.md
	    git status

  help:
	    @echo '"make boot" tangles all of the files in Template'
	    @echo '"make default" makes the .texi file, the .info file, \
	    the html files, and the .pdf file.'
	    @echo

	    @echo '"make check" checks for prerequistes'
	    @echo '"make values" runs check and prints variable values'
	    @echo

	    @echo '"make texi" makes the .texi file'
	    @echo '"make info" makes the .info file'
	    @echo '"make html" makes the html distribution in a subdirectory'
	    @echo '"make pdf" makes the .pdf file'
	    @echo

	    @echo '"make open-org" opens the ORG program using emacsclient for editing'
	    @echo '"make open-texi" opens the .texi file using emacsclient for review'
	    @echo '"make open-html" opens the distribution index.html file \
	    in the default web browser'
	    @echo '"make open-pdf" opens the .pdf file'
	    @echo

	    @echo '"make sync" syncs the html files in the AWS S3 bucket BUCKET; \
	    you must have your AWS S3 bucket name in the env var AWS_S3_BUCKET; \
	    You must have your AWS credentials installed in ~/.aws/credentials'
	    @echo

	    @echo '"make install-aws-cli" installs the "aws cli v2" command-line tools'
	    @echo 'You also need to run "aws configure" and supply your Access Key and Secret Access Key'
	    @echo

	    @echo '"make clean" removes the .texi, .info, and backup files ("*~")'
	    @echo '"make dist-clean" cleans, removes the html distribution, \
	    and removes the build directory'
	    @echo '"make wipe-clean" wipes clean the directory, including old directories'
	    @echo

	    @echo '"make delete-proj" deletes the project from the file system, GitHub and AWS'

#+end_src

*** TODO Next
1. The CloudFront configuration needs to be updated recognize the new version
   directory that is created as part of the ~sync~ operation.

2. Update the GitHub HOME website link for each new sync operation.

3. Store on GitHub a version of each other format upon a sync operation (i.e.,
   the INFO and PDF versions)

** Compare Replace

#+begin_comment
The following source code tangles all files during an export operation. This is
to  make  sure  the  ~cmprpl~  source code  exists  in  the  ~resources/tools/~
directory before running  the Makefile target =html=. It also  makes sure there
is a Makefile on an initial export. The following code is not exported.
#+end_comment

#+name:tangle-org-file
#+header: :exports results :eval yes :results silent
#+begin_src emacs-lisp
(org-babel-tangle-file (buffer-file-name))
#+end_src

The  AWS ~sync~  command  relies  upon time  stamps  to  determine whether  two
programs are identical or not, as  well as content.  If two otherwise identical
files have  different time stamps,  ~sync~ will  assume they are  different and
will  process the  newer.   However, the  ~texinfo~  ~makeinfo --html~  command
produces all  new files even  if some files  (or most files)  remain unchanged.
This  means that  all files  will be  uploaded to  the AWS  S3 bucket  on every
iteration, even though the majority of the files are actually unchanged.

The ~cmprpl~  source code attempts to  resolve the issue of  identical exported
code having different  time stamps, thus defeating the benefit  provided by the
~aws2 s3 sync~ command uploading only changed files.

This program makes sure that a generated HTML directory exists: =$DIR_NEW=.  If
it doesn’t, then it is in an improper state and the program stops with an error
message.

The  program then  checks  if  an old  directory  exists,  =$DIR_OLD=.  If  one
doesn’t,  then one  is  created by  copying the  current  new directory.   This
provides a baseline  for comparisons going forward.  The program  exits at that
point. It is very important that  the =$DIR_OLD= directory not be deleted going
forward.

Given  that =$DIR_OLD=  exists, the  program then  loops through  all files  in
=$DIR_NEW= and  compares them  to the  files in =$DIR_OLD=.   If the  files are
identical, the =$DIR_OLD= file replaces the =$DIR_NEW= file while retaining the
old time stamp (using the ~-p~ option of ~cp~. If a file is different, then the
=$DIR_NEW= file  replaces the =$DIR_OLD=  file, thus giving it  updated content
and  an updated  time stamp.   If the  file does  not exist  in the  =$DIR_OLD=
directory, then it is added.

The  program then  loops through  all of  the files  in the  old directory  and
deletes  any that  do not  exist in  the new  directory.  Now  both directories
should be in sync.

#+caption:Compare Replace program
#+name:cmprpl
#+header: :mkdirp t
#+header: :shebang "#!/usr/bin/env bash"
#+begin_src sh :tangle resources/tools/cmprpl
  [[ $# -eq 2 ]] || { echo "ERROR: Incorrect command line arguments"; exit 1; }
  DIR_NEW=$1
  DIR_OLD=$2

  [[ -d $DIR_NEW ]] || { echo "ERROR: $DIR_NEW does not exist"; exit 1; }
  [[ -d $DIR_OLD ]] || { echo "CREATING: $DIR_OLD does not exist"; cp -a $DIR_NEW $DIR_OLD; exit 0; }

  for newfile in $DIR_NEW/*
  do
      oldfile=$DIR_OLD/$(basename $newfile)
      if [[ -e $oldfile ]]
      then
	 if cmp -s $newfile $oldfile
	 then
	     printf "${GREEN}copying OLD to NEW${CLEAR}: "
	     cp -vp $oldfile $newfile
	 else
	     printf "${PURPLE}copying NEW to OLD${CLEAR}: "
	     cp -vp $newfile $oldfile
	 fi
      else
	  printf "${BLUE}creating NEW in OLD${CLEAR}: "
	  cp -vp $newfile $oldfile
      fi
  done

  for oldfile in $DIR_OLD/*
  do
      newfile=$DIR_NEW/$(basename $oldfile)
      if [[ ! -e $newfile ]]
      then
	  printf "${RED}removing OLD${CLEAR}: "
	  rm -v $oldfile
      fi
  done
#+end_src


** Update Utility Commands
*** Get Parsed Org Tree
This function looks for an Org file in the present working directory, and if it
finds one returns  a parsed tree using  ~org-element-parse-buffer~.  It returns
=nil= if there is no Org file or if the found file is not in ~org-mode~.

#+name:get-parsed-org-tree
#+header: :results silent
#+begin_src emacs-lisp
(defun get-parsed-org-tree (&optional org-dir)
  "This function takes an optional directory name, changes to
that directory if given, otherwise uses the pwd, and finds an Org
file and returns its parsed tree, or nil if none found."
  (when org-dir
      (cd (file-name-as-directory org-dir)))
  (let ((buf (car-safe (find-file-noselect "*.org" nil nil t))))
    (if buf
	(with-current-buffer buf (org-element-parse-buffer))
      nil)))
#+end_src

*** Check for CID
This code  checks whether an  Org file contains  a =custom_id= of  a particular
value.  It accepts  a ~cid-value~ and an optional directory.   If the directory
is not given, then it defaults to the current directory.  If throws an error if
the directory does not exist.  It returns =nil= if the given directory does not
contain an Org file.   It returns =t= if the Org file  contains a node property
of   =custom_id=  and   value  ~cid-value~,   or   =nil=  if   not.   It   uses
~get-parsed-org-tree~.

#+name:org-tree-cid-p
#+header: :results silent
#+begin_src emacs-lisp
(defun org-tree-cid-p (cid-value &optional org-dir)
  "Check whether an org file contains a custom_id of CID"
  (let ((tree (get-parsed-org-tree org-dir)))
    (car (org-element-map tree 'property-drawer
	   (lambda (pd) (org-element-map (org-element-contents pd) 'node-property
			  (lambda (np)
			    (and
			     (string= "custom_id" (org-element-property :key np))
			     (string= cid-value (org-element-property :value np))))))
	   nil t))))
#+end_src

#+name:run-org-tree-cid-p
#+header: :var cid="build-tools"
#+header: :var dir="/usr/local/dev/programming/MasteringEmacs"
#+header: :var gpot=get-parsed-org-tree()
#+header: :var otcp=org-tree-cid-p()
#+header: :results value
#+header: :eval never-export
#+begin_src emacs-lisp
(org-tree-cid-p cid dir)
#+end_src

#+call: run-org-tree-cid-p(dir="/usr/local/dev/programming/MasteringEmacs")

** Bucket Index HTML
The bucket should contain a master ~index.html~  file that links to each of the
individual project  ~index.html~ files.  The  master ~index.html~ file  will be
placed at the root of  the bucket, ~http/s://<bucket-name>.com/~, and the bucket
must be set up to serve this ~index.html~ when the user hits the root.

*** Get Bucket Name
 This  code searches  for  the keyword-value  pair =bucket:<BUCKET-NAME>=  that
 should be  located towards the  beginning of the  file, and returns  the value
 =BUCKET-NAME= or nil if not found.

#+name: get-bucket-name
#+header: :results value
#+begin_src emacs-lisp
   (save-excursion
     (goto-char (point-min))
     (re-search-forward "^#\\+bucket:\\s*?\\(.*\\)$" nil t)
     (match-string-no-properties 1))
#+end_src

For some reason, ~get-bucket-name~ does not  work when called from the headline
[[#project-index-links][=Links for  bucket=]] below  when creating  =index.html=, even  if it  returns as
~(prin1 ...)~ and is  set up to ~:return output~; the  call receives =nil=. The
following code from ~bucket-name~, however, works. I don't know why.

#+name: bucket-name
#+header: :results output
#+header: :var bucket-name=get-bucket-name()
#+begin_src emacs-lisp
(prin1 bucket-name)
#+end_src

*** Bucket HTTP/S URL
This  code calls  ~get-bucket-name~ and  returns the  value returned  as a  URL
string or nil.

#+name: bucket-http/s-url
#+header: :results value
#+header: :var b=get-bucket-name()
#+begin_src emacs-lisp
;; Need to set this according to the needs of the current bucket
(setq http/s "http")
(concat http/s "://" b)
#+end_src

*** S3 Bucket URL
This code calls ~get-bucket-name~ and returns the AWS S3 bucket url.

#+name: s3-bucket-url
#+header: :results value
#+header: :var b=get-bucket-name()
#+begin_src emacs-lisp
(concat "s3://" b)
#+end_src

*** Bucket Projects List
This code uses the ~s3-bucket-url~ result to obtain the list of projects in the
bucket.  It does  this by calling the  AWS S3 high-level command  ~ls~ and then
removing the  =PRE= string in  each result.  The result  that is returned  is a
single  string that  can be  separated into  individual links  by breaking  the
string on spaces.

#+name: bucket-projects-list
#+header: :results output
#+header: :var bucket=s3-bucket-url()
#+begin_src sh
/usr/local/bin/aws s3 ls ${bucket} | sed -ne 's/^.*PRE //p'
#+end_src

*** Bucket Project Links
This code  uses the result  from ~bucket-projects-list~ to create  an unordered
list of  links written to  bucket projects, written  in Org-mode syntax.  It is
executed by a =#+call:= in [[*Bucket Index][*Bucket  Index]] during an HTML export of that subtree
to a file called =index.html=.

#+name: bucket-project-links
#+header: :var b-url=bucket-http/s-url()
#+header: :var projects=bucket-projects-list()
#+header: :results output raw
#+begin_src emacs-lisp
(seq-do (lambda (u) (princ (format "- [[%s/%sindex.html][~%s~]]
" b-url u u))) (split-string projects))
#+end_src

*** Bucket Index
    :PROPERTIES:
    :custom_id: project-index-title
    :export_file_name: index.html
    :export_subtitle: {{{version}}} created {{{upload-date}}}
    :END:
#+html_doctype: html5
#+options: toc:nil html5-fancy:t

#+html: <hr>

**** Links for bucket call_bucket-name()
     :PROPERTIES:
     :unnumbered: t
     :custom_id: project-index-links
     :END:

#+call: bucket-project-links()
** Project Readme
This adds the README.md template to a project. It should be customized uniquely
for the project.

#+name:project-readme
#+header: :tangle README.md
#+begin_src markdown
# TITLE
## Subtitle
## Author
## Date
## Version
# ABSTRACT
This is the Org Template file.	It is the parent of all other Org Info blogs,
and provides the source code for processing them in various different ways.
# INTRODUCTION
# CHAPTER
## Section
### Subsection
#+end_src

** Boot Template
:PROPERTIES:
:dependency1: EMACS:=:/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs or similar
:dependency2: EDITOR:=:emacsclient
:dependency3: =SYNC_ORG_TEMPLATE= defined as $DEV/Templates/Org/Template.org
:END:
Although running the command ~org-babel-tangle~ (=C-c C-v t=) from within Emacs
will install  everything, it would  be nice to have  a simple Makefile  that is
downloaded with this  file that could be  invoked to do the  same thing without
starting Emacs and Org-mode and keying in the ~org-babel-tangle~ command.  This
little Makefile should be stored on  GitHub along with the ~Template.org~ file.
When  the source  is extracted  to a  directory, then  running this  Makefile's
default rule  as simply ~make~  will extract the ~preprocess.el~  script, which
updates  =DEV= and  then  extracts the  full Makefile.   Because  this file  is
tangled along with the full Makefile, it simply gets tacked onto the end of the
big Makefile as an additional rule.   Now, running ~make~ runs the default rule
from the  main Makefile, which is  to extract everything, then  export to TEXI,
INFO, HTML, and PDF forms.

It is assumed that an Emacs server is running, and that the $EDITOR environment
variable is set to use ~emacsclient~.

#+name:boot-template
#+header: :tangle Makefile
#+begin_src makefile
  boot:
	  $(EDITOR) -u --eval \
		  "(with-current-buffer (car (find-file-noselect \"./*.org\" nil nil t)) \
			  (goto-char (point-min)) \
			  (re-search-forward \"^#[+]name:preprocess.el$$\") \
			  (org-babel-tangle (quote (4))) \
			  (save-buffer) \
			  (kill-buffer))" \
	  --eval \
		  "(let ((rsrcdir \"resources\") \
			 (subdirs (list \"tools\" \"images\"))) \
		     (mkdir rsrcdir t) \
		     (dolist (subdir subdirs) (mkdir (concat rsrcdir \"/\" subdir) t)))"
	  ./resources/tools/preprocess.el
#+end_src

** Preprocess Env Vars
The environment variable DEV can be  in different locations and will be spelled
differently based  on how the  local machine is set  up.  For instance,  on one
system,  it will  be at  ~$HOME/Dev~  while in  another  system it  will be  at
~/usr/local/dev~.  However, the =:tangle= keyword  does not expand variables in
the form ~${DEV}~,  but rather requires absolute  paths, like ~/usr/local/dev~.
Therefore, this program works like a preprocessor for environment variables set
up  as part  of  =:tangle= lines,  changing them  to  their system  environment
variable values prior to tangling.  It lives in the ~resources/tools~ directory.

#+name:preprocess.el
#+header: :mkdirp t
#+header: :tangle resources/tools/preprocess.el
#+header: :shebang "#!/opt/local/bin/emacs -Q --script"
#+begin_src emacs-lisp
  (with-current-buffer (car (find-file-noselect "./*.org" nil nil t))
    (save-excursion
    (goto-char (point-min))
    (let ((re-search-str "\\(?::tangle\\|load-file \\(?:[\\]*\\)?[\"]\\)\s*\\(.*?/[dD]ev\\)/")
          (dev (getenv "DEV")))
      (while
              (re-search-forward re-search-str nil t)
              (replace-match dev t nil nil 1)))
    (save-buffer)
    (require 'org)
    (org-babel-tangle)))
#+end_src

** Samples
#+begin_comment
(cd "~/Dev/Emacs/MasteringEmacs/")
"/Users/pine/Dev/Emacs/MasteringEmacs/"

(defun add-bucket (org bucket)
  "Add a bucket keyword BUCKET to the org file ORG."
  (interactive "fFile: \nsBUCKET: ")
  (with-current-buffer (find-file-noselect org)
    (let* ((tree (org-element-parse-buffer))
	   (ins (car (org-element-map tree (quote section)
		 (lambda (s)
		   (org-element-map s (quote keyword)
		     (lambda (kw) (when (equal "MACRO" (org-element-property :key kw)) (1- (org-element-property :end kw))))
		     nil nil :keyword))
		 nil t nil nil))))
      (goto-char ins)
      (insert (format "#+bucket:%s\n" bucket))
      ())))

(add-bucket "MasteringEmacs.org" "pinecone-forest")
nil

(defun hl-region (raw-hl)
  "Obtain the begin and end positions for a headline."
  (with-current-buffer (find-file-noselect (getenv "SYNC_ORG_TEMPLATE"))
    (let* ((tree (get-parsed-tree))
	   (hl (car-safe (org-element-map tree 'headline
			   (lambda (hl) (when
					    (string= raw-hl
						     (org-element-property :raw-value hl))
					  (org-element-context)))
			   nil nil t))))
      (cons
       (org-element-property :begin hl)
       (org-element-property :end hl))
      )))

(hl-region "Build Tools")

(4888 . 29646)

(defun get-hl-with-prop (org-dir hl-prop)
  "Given a directory containing an Org template file and a custom_id property name, return the headline containing that custom_id, or nil if none."
  (progn
    (cd org-dir)
    (let ((org-buf (car-safe (find-file-noselect "*.org" nil nil t))))
      (if org-buf
	  (with-current-buffer org-buf
	    (let ((tree (org-element-parse-buffer)))
	      (org-element-map tree 'headline
		(lambda (hl)
		  (let ((cid (org-element-property :CUSTOM_ID hl)))
		    (when (string= hl-prop cid)
		      (and
		       (message (format "Found the headline %s containing property %s." (org-element-property :raw-value hl) hl-prop))
		       hl))))
		nil t)))
	(and
	 (message (format "The directory %s does not contain an Org file." org-dir))
	 nil)))))

(get-hl-with-prop "~/Dev/Templates/Org" "build-tools")

(headline (:raw-value "Build Tools" :begin 4888 :end 29646 :pre-blank 0 :contents-begin 4902 :contents-end 29645 :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 1 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 4888 :FROM-FILE "Template" :CUSTOM_ID "build-tools" :APPENDIX "t" :title "Build Tools"))









;;; Add a keyword named 'bucket' just after the version macro.
;;; This function should be run from within the directory containing the Org file.
(defun add-bucket (org-file s3-bucket)
  "Add the name of the associated AWS S3 bucket to an Org templated file."
  (with-current-buffer (find-file-noselect org-file)
    (goto-char (point-min))
    (let* ((tree (org-element-parse-buffer))
	   ;; find the beginning position of the first headline to act as a limit
	   (hl1 (org-element-map tree (quote headline) (lambda (hl) (org-element-property :begin hl)) nil t)))
      ;; Check for the presence of a bucket keyword before the first headline
      (unless (re-search-forward "^#\\+bucket:" hl1 t)
	;; If no bucket keyword is found, search for a keyword MACRO with the value 'version'
	(org-element-map tree (quote keyword)
	  (lambda (kw) (when (and (string= "MACRO" (org-element-property :key kw))
				  (string-match-p "version" (org-element-property :value kw)))
			 ;; return the end position of the MACRO; subtract an empty line if there is one
			 (goto-char (- (org-element-property :end kw) (org-element-property :post-blank kw)))
			 (insert "#+bucket:" s3-bucket)
			 (newline)
			 (basic-save-buffer)
			 (message (format "Added bucket %s" s3-bucket))))
	  nil t)))))

(add-bucket "MasteringEmacs.org" "pinecone-forest.com")
nil

"Added bucket pinecone-forest.com"









(keyword (:key "MACRO" :value "version Version 0.0.108" :begin 148 :end 181 :post-blank 1 :post-affiliated 148 ...))
("TITLE" "SUBTITLE" "AUTHOR" "DATE" "MACRO" "TEXINFO" "TEXINFO" "CINDEX" "CINDEX" "CINDEX" "CINDEX" "CINDEX" ...)







((keyword (:key "MACRO" :value "version Version 0.0.107" :begin 148 :end 181 :post-blank 1 :post-affiliated 148 ...)))
#+end_comment

* List of Programs
:PROPERTIES:
:appendix: t
:END:
#+texinfo:@listoffloats Listing

* List of Examples
:PROPERTIES:
:appendix: t
:END:
#+texinfo:@listoffloats Example

* Copying
:PROPERTIES:
:copying:  t
:END:

Copyright \copy 2020 by {{{author}}}

* Concept Index
:PROPERTIES:
:index:	cp
:END:

* Program Index
:PROPERTIES:
:index:	pg
:END:

* Function Index
:PROPERTIES:
:index:	fn
:END:

* Variable Index
:PROPERTIES:
:index:	vr
:END:


* Configuration							   :noexport:
#+startup:content

#+todo: SOMEDAY(s@) TODO(t@) INPROGRESS(i@) WAIT(w@) | CANCEL(c@) DONE(d!)

#+options: H:4

#+texinfo_class: info
#+texinfo_header:
#+texinfo_post_header:
#+texinfo_dir_category:<DIR CATEGORY>
#+texinfo_dir_title:<DIR TITLE>
#+texinfo_dir_desc:<DIR DESCRIPTION>
#+texinfo_printed_title:EstatePlanning---LOLH

#+latex_class: article
#+latex_class_options:[12pt]
#+latex_header: \usepackage[margin=1.25in]{geometry}
#+latex_header_extra:
#+description:
#+keywords:
#+latex_compiler: xelatex
#+date: \today


* Footnotes

[fn:1]In the browser, add =index.text= to the end of the URL to see the source.

[fn:2]Markdown requires the standard Perl library module Digest::MD5.


* Local Variables						   :noexport:
# Local Variables:
# fill-column: 79
# indent-tabs-mode: t
# eval: (auto-fill-mode)
# time-stamp-pattern: "8/^\\#\\+date:%:y-%02m-%02d %02H:%02M$"
# End:
